#!/bin/sh

HARE_VERSION=${1:-unknown}

RELEASE_ROOT=`pwd`/..
REFACTORER=${RELEASE_ROOT}/refactorer/pfe
REFACTORER_CLIENT=${RELEASE_ROOT}/refactorer/pfe_client
PRELUDE=${RELEASE_ROOT}/tools/base/tests/HaskellLibraries
GHC_PATH=`ghc --print-libdir`


case `uname` in
  CYGWIN*)
    REFACTORER=`cygpath -wa ${REFACTORER} | sed 's/\( \|\\\\\)/\\\\\1/g'`
    REFACTORER_CLIENT=`cygpath -wa ${REFACTORER_CLIENT} | sed 's/\( \|\\\\\)/\\\\\1/g'`
    PRELUDE=`cygpath -wa ${PRELUDE} | sed 's/\( \|\\\\\)/\\\\\1/g'`
    GHC_PATH=`cygpath -wa ${GHC_PATH} | sed 's/\( \|\\\\\)/\\\\\1/g'` 
    ;;
  *)
    CURRENT=`pwd`
    cd `dirname ${REFACTORER}`; REFACTORER=`pwd`/pfe  
    cd `dirname ${REFACTORER_CLIENT}`; REFACTORER_CLIENT=`pwd`/pfe_client
    cd `dirname ${PRELUDE}`; PRELUDE=`pwd`/HaskellLibraries
    cd ${CURRENT}
    ;;
esac
cat >LocalSettings.hs <<SETTINGS
module LocalSettings where

hare_version="${HARE_VERSION}"
release_root= showNoQuotes "${RELEASE_ROOT}"
refactorer = showNoQuotes "${REFACTORER}"
refactorer_client = showNoQuotes "${REFACTORER_CLIENT}"
preludePath = "${PRELUDE}"

reportFilePath = "${RELEASE_ROOT}/refactorer/duplicate/report.txt"
answerFilePath = "${RELEASE_ROOT}/refactorer/duplicate/answers.txt"
positionFilePath = "${RELEASE_ROOT}/refactorer/duplicate/positions.txt"
transFilePath  = "${RELEASE_ROOT}/refactorer/duplicate/transforms.txt"
classAnswerPath    = "${RELEASE_ROOT}/refactorer/duplicate/classAnswer.txt"
classTransformPath = "${RELEASE_ROOT}/refactorer/duplicate/classTransform.txt"
mergeFilePath  = "${RELEASE_ROOT}/refactorer/merging/mergeCache.txt"
ghcPath = "$GHC_PATH"
evalFilePath = "${RELEASE_ROOT}/refactorer/evalMon/evalCache.txt"
evaluate = "${RELEASE_ROOT}/refactorer/evaluate"
evaluate_result = "${RELEASE_ROOT}/refactorer/evaluate_result"

genFoldPath = "${RELEASE_ROOT}/refactorer/genFoldCache.txt"

(refactor_prg:refactor_args) = words refactorer -- for emacs
showNoQuotes x = init $ tail $ show x
SETTINGS


