################################ -*- Ruby -*- #################################
# Common tasks
#

package = "font-lock-studio"

desc "Generate README.md"
task "readme" do
  sh "emacs", "-batch",
     "-L", "../../el2markdown",
     "-l", "../../font-lock-tools-admin/font-lock-tools-admin.el",
     "../#{package}.el",
     "-f", "font-lock-tools-admin-write-readme"
end

desc "Generating html"
task "html" => ["readme"] do
  sh "Markdown.pl ../README.md > ../README.html"
end

desc "Byte compile"
task "compile" do
  sh "emacs -batch -f batch-byte-compile ../#{package}.el"
end
