#!/bin/bash

cd ~/.emacs.d

DIRS="override lib lisp site-lisp"

echo ========================================
echo Installed, but not in Git
echo ========================================
comm -23 <(find $DIRS -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort) \
         <((git remote; git submodule status | awk '{print $2}') | egrep '^(ext|lisp|site-lisp)/' | perl -pe 's/^(ext|lisp|site-lisp)\///' | sort)

echo ========================================
echo In Git, but not installed
echo ========================================
comm -13 <(find $DIRS -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | sort) \
         <((git remote; git submodule status | awk '{print $2}') | egrep '^(ext|lisp|site-lisp)/' | perl -pe 's/^(ext|lisp|site-lisp)\///' | sort)

echo ========================================
echo Installed, but not used
echo ========================================
comm -23 <(find $DIRS -maxdepth 1 -mindepth 1 \( -name '*.el' -o -type d \) -exec basename {} \; | sed 's/\.el//' | sed 's/^emacs-//' | sort) \
         <(perl -ne 'print $1, "\n" if /use-package ([A-Za-z0-9_+-]+)/;' *.el | sort)

echo ========================================
echo Used, but not installed
echo ========================================
comm -13 <(find -L ~/.nix-profile/share/emacs/ $DIRS \( -name '*.elc' -o -type d \) -exec basename {} \; | sed 's/\.elc//' | sed 's/^emacs-//' | sort | uniq) \
         <(perl -ne 'print $1, "\n" if /use-package ([A-Za-z0-9_+-]+)/;' *.el | sed '/^dot-/d' | sort | uniq)

# echo In Git, but not used
# comm -23 <(git remote | grep ^ext/ | sed 's/^ext\///' | sort) \
#          <(perl -ne 'print $1, "\n" if /use-package ([A-Za-z0-9_+-]+)/;' *.el | sort)

# echo Used, but not in Git
# comm -13 <(git remote | grep ^ext/ | sed 's/^ext\///' | sort) \
#          <(perl -ne 'print $1, "\n" if /use-package ([A-Za-z0-9_+-]+)/;' *.el | sort)
