#!/bin/bash -e

find "$@"                                                                                       \
    \( \( \( -name .git                                                                         \
          -o -name doc                                                                          \
          -o -name dev                                                                          \
          -o -name test                                                                         \
          -o -name tests                                                                        \
          -o -name testing                                                                      \
          -o -name shimbun                                                                      \
          -o -name obsolete                                                                     \
          -o -name examples                                                                     \
          -o -name samples                                                                      \
          -o -name gnus-fallback-lib                                                            \
          -o -name support                                                                      \
          -o -name targets                                                                      \
          -o -name style \) -prune \)                                                           \
       -o -name '*.el' \)                                                                       \
       -name '*.el'                                                                             \
       ! -name '.*'                                                                             \
       ! -name '*-test.el'                                                                      \
       ! -name '*-tests.el'                                                                     \
       ! -path lib/elisp-refs/elisp-refs-bench.el                                               \
       ! -path lib/emacs-web/web-file-upload.el                                                 \
       ! -path lib/esxml/css-lite.el                                                            \
       ! -path lib/esxml/esxml-form.el                                                          \
       ! -path lib/esxml/esxpath.el                                                             \
       ! -path lib/f-el/bin/docs.el                                                             \
       ! -path lisp/muse/contrib/htmlize-hack.el                                                \
       ! -path lisp/my-one-key.el                                                               \
       ! -path lisp/puppet-ext.el                                                               \
       ! -path lisp/springboard/springboard.el                                                  \
       ! -path site-lisp/company-coq/etc/rebuild-screenshots.el                                 \
       ! -path site-lisp/company-coq/etc/screenshots.el                                         \
       ! -path site-lisp/company-ghc/company-ghc.el                                             \
       ! -path site-lisp/dired-hacks/dired-images.el                                            \
       ! -path site-lisp/emacs-calfw/calfw-howm.el                                              \
       ! -path 'site-lisp/emacs-cl/src/*.el'                                                    \
       ! -path site-lisp/emacs-w3m/mew-w3m.el                                                   \
       ! -path site-lisp/emacs-w3m/mime-w3m.el                                                  \
       ! -path site-lisp/emacs-w3m/octet.el                                                     \
       ! -path site-lisp/emacs-w3m/w3m-ucs.el                                                   \
       ! -path site-lisp/emacs-w3m/w3m-xmas.el                                                  \
       ! -path site-lisp/eval-in-repl/eval-in-repl-cider.el                                     \
       ! -path site-lisp/eval-in-repl/eval-in-repl-elm.el                                       \
       ! -path site-lisp/eval-in-repl/eval-in-repl-erlang.el                                    \
       ! -path site-lisp/eval-in-repl/eval-in-repl-geiser.el                                    \
       ! -path site-lisp/eval-in-repl/eval-in-repl-hy.el                                        \
       ! -path site-lisp/eval-in-repl/eval-in-repl-iex.el                                       \
       ! -path site-lisp/eval-in-repl/eval-in-repl-javascript.el                                \
       ! -path site-lisp/eval-in-repl/eval-in-repl-racket.el                                    \
       ! -path site-lisp/eval-in-repl/eval-in-repl-scala.el                                     \
       ! -path site-lisp/eval-in-repl/eval-in-repl-sml.el                                       \
       ! -path site-lisp/gnus/lisp/gnus-xmas.el                                                 \
       ! -path site-lisp/lentic/build.el                                                        \
       ! -path site-lisp/lua-mode/lua-mode.el                                                   \
       ! -path site-lisp/nix-mode/nix-mode-mmm.el                                               \
       ! -path site-lisp/org-mode/contrib/lisp/org-jira.el                                      \
       ! -path site-lisp/popwin/misc/popwin-yatex.el                                            \
       ! -path site-lisp/python-mode/completion/auto-complete-pycomplete.el                     \
       ! -path site-lisp/python-mode/completion/company-pycomplete.el                           \
       ! -path site-lisp/python-mode/devel/fundocu2infoformats.el                               \
       ! -path site-lisp/restclient/restclient-helm.el                                          \
       ! -path site-lisp/smart-mode-line/themes/smart-mode-line-light-powerline-theme.el        \
       ! -path site-lisp/smart-mode-line/themes/smart-mode-line-powerline-theme.el              \
       -type f -print0 |                                                                        \
                                                                                                \
    xargs -0 $BATCH_LOAD                                                                        \
          -L site-lisp/agda/src/data/emacs-mode                                                 \
          -L site-lisp/org-mode/contrib/lisp                                                    \
          -L site-lisp/password-store/contrib/emacs                                             \
          -f batch-byte-compile-if-not-done

# if [[ "$1" == --leq ]]; then
#     rm -fr compiled
#     mkdir compiled
#     cd compiled

#     find ../lib ../lisp ../site-lisp                            \
#       \(    -ipath ../site-lisp/auctex/style -prune             \
#          -o -ipath ../site-lisp/slime -prune                    \
#          -o -ipath ../site-lisp/evil/lib -prune                 \
#          -o -ipath ../site-lisp/emacs-cl -prune                 \
#          -o -ipath ../site-lisp/emacs-w3m/shimbun -prune        \
#          -o -ipath ../site-lisp/hyperbole -prune                \
#          -o -ipath ../site-lisp/proof-general -prune            \
#                                                                 \
#          -o -name dev -prune                                    \
#          -o -name ert-tests -prune                              \
#          -o -name examples -prune                               \
#          -o -name features -prune                               \
#          -o -name helpers -prune                                \
#          -o -name samples -prune                                \
#          -o -name targets -prune                                \
#          -o -name test -prune                                   \
#          -o -name tests -prune                                  \
#                                                                 \
#          -o    -name '*.el'                                     \
#             \! -name '.*'                                       \
#             \! -name '*debbug*.el'                              \
#             \! -name '*-tests.el'                               \
#             \! -name '*-test.el'                                \
#             \! -name '*-pkg.el'                                 \
#             \! -name auto-complete-pycomplete.el                \
#             \! -name build.el                                   \
#             \! -name calfw-howm.el                              \
#             \! -name company-pycomplete.el                      \
#             \! -name css-lite.el                                \
#             \! -name company-ghc.el                             \
#             \! -name dired-images.el                            \
#             \! -name direx-ctable.el                            \
#             \! -name docs.el                                    \
#             \! -name elisp-refs-bench.el                        \
#             \! -name elpa.el                                    \
#             \! -name ert.el                                     \
#             \! -name esxml-form.el                              \
#             \! -name esxpath.el                                 \
#             \! -name eval-in-repl-cider.el                      \
#             \! -name eval-in-repl-elm.el                        \
#             \! -name eval-in-repl-erlang.el                     \
#             \! -name eval-in-repl-geiser.el                     \
#             \! -name eval-in-repl-hy.el                         \
#             \! -name eval-in-repl-iex.el                        \
#             \! -name eval-in-repl-javascript.el                 \
#             \! -name eval-in-repl-racket.el                     \
#             \! -name eval-in-repl-scala.el                      \
#             \! -name eval-in-repl-slime.el                      \
#             \! -name eval-in-repl-sml.el                        \
#             \! -name fundocu2infoformats.el                     \
#             \! -name haskell-gifcasts.el                        \
#             \! -name le-clojure.el                              \
#             \! -name mew-w3m.el                                 \
#             \! -name mime-w3m.el                                \
#             \! -name octet.el                                   \
#             \! -name org-jira.el                                \
#             \! -name popwin-yatex.el                            \
#             \! -name smart-mode-line-light-powerline-theme.el   \
#             \! -name smart-mode-line-powerline-theme.el         \
#             \! -name test-ctable.el                             \
#             \! -name test-org-src.el                            \
#             \! -name test.el                                    \
#             \! -name tests.el                                   \
#             \! -name w3m-ucs.el                                 \
#             \! -name w3m-xmas.el                                \
#             \! -name web-file-upload.el                         \
#             \! -name setup-ox-hugo.el                           \
#       \)                                                        \
#       -name '*.el'                                              \
#       -type f                                                   \
#                                                                 \
#       | parallel cp -p {} .

#     cd ..
# fi

# cd compiled
# parallel -j8 emacs -batch \
#                    -L . \
#                    -L ../site-lisp/proof-general \
#                    -L ../site-lisp/proof-general/lib \
#                    -L ../site-lisp/proof-general/generic \
#                    -f batch-byte-compile-if-not-done {} ::: *.el
