#!/bin/bash -e

find "$@"                                                       \
    \( \( \( -name .git                                         \
          -o -name doc                                          \
          -o -name dev                                          \
          -o -name test                                         \
          -o -name tests                                        \
          -o -name testing                                      \
          -o -name shimbun                                      \
          -o -name obsolete                                     \
          -o -name examples                                     \
          -o -name gnus-fallback-lib                            \
          -o -name support                                      \
          -o -name targets                                      \
          -o -name style \) -prune \)                           \
       -o -name '*.el' \)                                       \
       -name '*.el'                                             \
       ! -name '.*'                                             \
       ! -name '*-test.el'                                      \
       ! -name '*-tests.el'                                     \
       ! -path lib/f-el/bin/docs.el                             \
       ! -path lib/pos-tip/sdic-inline-pos-tip.el               \
       ! -path lisp/muse/contrib/htmlize-hack.el                \
       ! -path lisp/my-one-key.el                               \
       ! -path lisp/puppet-ext.el                               \
       ! -path lisp/springboard/springboard.el                  \
       ! -path site-lisp/emacs-w3m/mew-w3m.el                   \
       ! -path site-lisp/emacs-w3m/mime-w3m.el                  \
       ! -path site-lisp/emacs-w3m/octet.el                     \
       ! -path site-lisp/emacs-w3m/w3m-ucs.el                   \
       ! -path site-lisp/emacs-w3m/w3m-xmas.el                  \
       ! -path site-lisp/lentic/build.el                        \
       ! -path site-lisp/popwin/misc/popwin-yatex.el            \
       ! -path site-lisp/restclient/restclient-helm.el          \
       ! -path site-lisp/company-coq/etc/rebuild-screenshots.el \
       ! -path site-lisp/company-coq/etc/screenshots.el         \
       ! -path site-lisp/lua-mode/lua-mode.el                   \
       ! -path site-lisp/company-ghc/company-ghc.el             \
       ! -path site-lisp/dired-hacks/dired-images.el            \
       ! -path site-lisp/gnus/lisp/gnus-xmas.el                 \
       ! -path site-lisp/nix-mode/nix-mode-mmm.el               \
       ! -path site-lisp/emacs-calfw/calfw-howm.el              \
       ! -path site-lisp/org-mode/contrib/lisp/org-jira.el      \
       -type f -print0 |                                        \
    xargs -0 $BATCH_LOAD                                        \
          -L site-lisp/agda/src/data/emacs-mode                 \
          -L site-lisp/org-mode/contrib/lisp                    \
          -f batch-byte-compile-if-not-done
