.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EMMS-PRINT-METADATA 1 "April 29, 2006" EMMS
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
emms-print-metadata \- Print information about music files
.SH SYNOPSIS
.B emms-print-metadata
.RI file.ext
.br
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
\fBemms-print-metadata\fP will print metadata about music files to
stdout, to be used primarily by EMMS, the Emacs MultiMedia System.
.SH SEE ALSO
.BR emms (info)
.br
.SH AUTHOR
emms-print-metadata was written by Trent Buck.
