##
## Makefile for Proof General XEmacs package.
## 
## Author:  David Aspinall <da@dcs.ed.ac.uk>
##
## Maintainer:  Proof General maintainer <proofgen@dcs.ed.ac.uk>
##
## $Id$
##
## Developer use only, not part of distribution.
##
##   make pkg	- Make XEmacs format package of Proof General
## 

