#!/bin/bash -e

if [[ "$1" == --files ]]; then
    cat MANIFEST.csv                                \
        | grep ',file,'                             \
        | grep -v ',part,'                          \
        | grep -v ',unknown,'                       \
        | grep -v mirror-only                       \
        | grep -v internal                          \
        | grep -v elpa                              \
        | while read line; do
        FILE=$(echo $line | cut -d, -f1)
        DIR=$(echo $line | cut -d, -f2)
        URL=$(echo $line | cut -d, -f4)
        if [[ -f $DIR/$FILE ]]; then
            echo curl -o $DIR/$FILE $URL
            curl -o $DIR/$FILE $URL
        fi
    done

elif [[ "$1" == --remotes ]]; then
    git fetch --all --no-tags
    
elif [[ "$1" == --subtrees ]]; then
    cat MANIFEST.csv                                \
        | grep ',subtree,'                          \
        | grep -v mirror-only                       \
        | grep -v internal                          \
        | grep -v elpa                              \
        | while read line; do
        MODULE=$(echo $line | cut -d, -f1)
        DIR=$(echo $line | cut -d, -f2)
        echo git pulltree $DIR/$MODULE
        git pulltree $DIR/$MODULE
    done
fi
