#!/bin/bash -e

cat MANIFEST.csv                                \
    | grep ',subtree,'                          \
    | grep -v mirror-only                       \
    | while read line; do
    MODULE=$(echo $line | cut -d, -f1)
    DIR=$(echo $line | cut -d, -f2)
    echo git pulltree $DIR/$MODULE
    git pulltree $DIR/$MODULE
done
