#+TITLE: CHANGELOG
#+AUTHOR: DogLooksGood

* v0.4.0
- bugfix.
- remove ~company~ extension, instead add ~defaults~.
- improve ~smart-tab~.
- short document.

* v0.3.2
- bugfix.
- ~smart-tab~ extension.

* v0.3.1
- bugfix.
- ~smart-yank~ extension.

* v0.3.0
- bugfix.
- Refactor code.
- Extension module.

* v0.2.0
- Add ~parinfer-skip-command-list~, ~parinfer-skip-command-prefix-list~, ~parinfer-instantly-invoke-command-list~, ~parinfer-instantly-invoke-command-prefix-list~.
- Compatibility with Evil. 
- BUGFIX: Broken ~Package-Requires~. 

* v0.1.4
- Delay processing on large S-expression. customize with ~parinfer-delay-invoke-threshold~ and ~parinfer-delay-invoke-idle~.

* v0.1.3
- Rename all private function with the prefix ~parinfer--~ instead of ~parinfer-~.
- Remove paredit dependencies sine we don't neet it.
- Add group for parinfer-theme.el, fix the compile warnnings ~defface `parinfer-dim-paren-face' fails to specify containing group~.

* v0.1.2
- Fix lag when move cursor in a very large sexp(especially when holding ~C-n~ or ~C-p~).

