#!/bin/sh
RELEASE_ROOT=${RELEASE_ROOT-..}

. $RELEASE_ROOT/refactorer/HuMakefile

SYSTEM=`uname`

case `uname` in
  CYGWIN*)
    ghc --make $GHCFLAGS -cpp -fno-cse -fglasgow-exts -XFunctionalDependencies -XMultiParamTypeClasses -XOverlappingInstances -XUndecidableInstances -XNoMonomorphismRestriction -package network -package ghc -i../editors/ -odir odir/$SYSTEM -hidir hidir/$SYSTEM -osuf o -hisuf hi Evaluate.hs -o evaluate
    ghc --make $GHCFLAGS -cpp -fglasgow-exts -XMultiParamTypeClasses -XFunctionalDependencies -XOverlappingInstances -XUndecidableInstances -XNoMonomorphismRestriction -package ghc -package network -i${SRC_DIRS} -odir odir/$SYSTEM -hidir hidir/$SYSTEM -osuf o -hisuf hi $*
    ;;
  SunOS*)
    ghc --make $GHCFLAGS -cpp -fno-cse -fglasgow-exts -XMultiParamTypeClasses -XOverlappingInstances -XFunctionalDependencies -XUndecidableInstances -XNoMonomorphismRestriction -package network -package ghc -i${SRC_DIRS} -odir odir/$SYSTEM -hidir hidir/$SYSTEM -osuf o -hisuf hi Evaluate.hs -o evaluate
    ghc --make $GHCFLAGS -cpp -fglasgow-exts -XMultiParamTypeClasses -XOverlappingInstances -XUndecidableInstances -XFunctionalDependencies -XNoMonomorphismRestriction -package ghc -package network -i${SRC_DIRS} -odir odir/$SYSTEM -hidir hidir/$SYSTEM -osuf o -hisuf hi $*
    ;;
  *)
    # default case for unixish systems, confirmed for Mac OS X (10.2.6), Linux (Redhat, Mandrake)
    ghc --make $GHCFLAGS -cpp -fno-cse -fglasgow-exts -XMultiParamTypeClasses -XOverlappingInstances -XUndecidableInstances -XFunctionalDependencies -XNoMonomorphismRestriction -package network -package ghc -i../editors/  Evaluate.hs -o evaluate
    ghc --make $GHCFLAGS -cpp -fno-cse -fglasgow-exts -XMultiParamTypeClasses -XOverlappingInstances -XUndecidableInstances -XFunctionalDependencies -XNoMonomorphismRestriction -package network -package ghc -i${SRC_DIRS} -odir odir/$SYSTEM -hidir hidir/$SYSTEM -osuf o -hisuf hi $*
   
    ;;
esac

