#!/bin/sh

PATH_ELEMS="$(echo ${PATH} | tr -s ':' '\n')"

ORIG_RUNGHC_BINARY=""

for PATH_ELEM in ${PATH_ELEMS}; do
    RUNGHC_CANDIDATE="${PATH_ELEM}/runghc"
    if command -v "${RUNGHC_CANDIDATE}" > /dev/null 2> /dev/null; then
        if [ "${0}" != "${RUNGHC_CANDIDATE}" ]; then
            if [ -z "${ORIG_RUNGHC_BINARY}" ]; then
                ORIG_RUNGHC_BINARY="${RUNGHC_CANDIDATE}"
            fi
        fi
    fi
done

if [ -z "${ORIG_RUNGHC_BINARY}" ]; then
    echo "runghc wrapper: Couldn't find real runghc program"
    exit 1
fi

exec "$ORIG_RUNGHC_BINARY" ${PACKAGE_DB_FOR_GHC} "$@"
