Require Import Bvector.
Require Import DecBool.
Require Import Bool.
Require Import BoolEq.
Require Import Zerob.
Require Import Setoid.
Require Import Utf8.
Require Import Utf8_core.
Require Import Mergesort.
Require Import Reals.
Require Import Sorting.
Require Import Sorted.
Require Import Heap.
Require Import Permutation.
Require Import PermutSetoid.
Require Import PermutEq.
Require Import ZBinary.
Require Import ZSigZAxioms.
Require Import ZSig.
Require Import ZMulOrder.
Require Import ZLcm.
Require Import ZLt.
Require Import ZAxioms.
Require Import ZSgnAbs.
Require Import ZDivEucl.
Require Import ZBase.
Require Import ZDivFloor.
Require Import ZAddOrder.
Require Import ZParity.
Require Import ZProperties.
Require Import ZAdd.
Require Import ZMaxMin.
Require Import ZMul.
Require Import ZGcd.
Require Import ZPow.
Require Import ZBits.
Require Import ZDivTrunc.
Require Import BigZ.
Require Import ZMake.
Require Import ZNatPairs.
Require Import BigNumPrelude.
Require Import ZModulo.
Require Import DoubleSub.
Require Import DoubleMul.
Require Import DoubleType.
Require Import DoubleBase.
Require Import DoubleDivn1.
Require Import DoubleAdd.
Require Import DoubleDiv.
Require Import DoubleCyclic.
Require Import DoubleSqrt.
Require Import DoubleLift.
Require Import Int31.
Require Import Ring31.
Require Import Cyclic31.
Require Import CyclicAxioms.
Require Import NZCyclic.
Require Import BinNums.
Require Import QMake.
Require Import BigQ.
Require Import QSig.
Require Import NumPrelude.
Require Import NaryFunctions.
Require Import NBinary.
Require Import NMake_gen.
Require Import Nbasic.
Require Import BigN.
Require Import NMake.
Require Import NSigNAxioms.
Require Import NSig.
Require Import NPeano.
Require Import NAddOrder.
Require Import NIso.
Require Import NProperties.
Require Import NAdd.
Require Import NOrder.
Require Import NLcm.
Require Import NSqrt.
Require Import NStrongRec.
Require Import NParity.
Require Import NLog.
Require Import NSub.
Require Import NDefOps.
Require Import NBase.
Require Import NPow.
Require Import NMulOrder.
Require Import NMaxMin.
Require Import NBits.
Require Import NGcd.
Require Import NAxioms.
Require Import NDiv.
Require Import NZDiv.
Require Import NZParity.
Require Import NZPow.
Require Import NZProperties.
Require Import NZOrder.
Require Import NZAdd.
Require Import NZGcd.
Require Import NZDomain.
Require Import NZAxioms.
Require Import NZLog.
Require Import NZAddOrder.
Require Import NZMulOrder.
Require Import NZBase.
Require Import NZMul.
Require Import NZBits.
Require Import NZSqrt.
Require Import Pnat.
Require Import BinPosDef.
Require Import BinPos.
Require Import POrderedType.
Require Import PArith.
Require Import Zwf.
Require Import Zcompare.
Require Import Zpower.
Require Import Zmisc.
Require Import Zsqrt_compat.
Require Import Int.
Require Import Zmax.
Require Import Zgcd_alt.
Require Import ZArith.
Require Import auxiliary.
Require Import Zeuclid.
Require Import ZArith_base.
Require Import Zminmax.
Require Import Wf_Z.
Require Import ZOdiv.
Require Import Zpow_alt.
Require Import BinIntDef.
Require Import Zorder.
Require Import Zpow_facts.
Require Import Zbool.
Require Import BinInt.
Require Import Zcomplements.
Require Import Znat.
Require Import Zquot.
Require Import Zdigits.
Require Import Zabs.
Require Import Zmin.
Require Import ZOdiv_def.
Require Import Zhints.
Require Import ZArith_dec.
Require Import Zpow_def.
Require Import Zeven.
Require Import Zdiv.
Require Import Znumtheory.
Require Import Zlogarithm.
Require Import Arith_base.
Require Import Compare.
Require Import Euclid.
Require Import Gt.
Require Import Compare_dec.
Require Import Wf_nat.
Require Import Min.
Require Import Even.
Require Import Bool_nat.
Require Import Plus.
Require Import Le.
Require Import EqNat.
Require Import Mult.
Require Import Arith.
Require Import Peano_dec.
Require Import Lt.
Require Import Minus.
Require Import Factorial.
Require Import Div2.
Require Import Between.
Require Import Max.
Require Import Utils.
Require Import Syntax.
Require Import Program.
Require Import Combinators.
Require Import Tactics.
Require Import Basics.
Require Import Equality.
Require Import Subset.
Require Import Logic.
Require Import Logic_Type.
Require Import Peano.
Require Import Notations.
Require Import Tactics.
Require Import Datatypes.
Require Import Prelude.
Require Import Specif.
Require Import Inclusion.
Require Import Wellfounded.
Require Import Inverse_Image.
Require Import Lexicographic_Product.
Require Import Union.
Require Import Lexicographic_Exponentiation.
Require Import Transitive_Closure.
Require Import Disjoint_Union.
Require Import Well_Ordering.
Require Import FMaps.
Require Import FSetInterface.
Require Import FSets.
Require Import FMapAVL.
Require Import FSetList.
Require Import FMapList.
Require Import FSetWeakList.
Require Import FMapPositive.
Require Import FMapInterface.
Require Import FSetAVL.
Require Import FSetPositive.
Require Import FSetDecide.
Require Import FSetBridge.
Require Import FSetFacts.
Require Import FSetEqProperties.
Require Import FMapWeakList.
Require Import FMapFacts.
Require Import FSetCompat.
Require Import FSetToFiniteSet.
Require Import FMapFullAVL.
Require Import FSetProperties.
Require Import Qfield.
Require Import Qreduction.
Require Import Qround.
Require Import Qminmax.
Require Import Qpower.
Require Import Qreals.
Require Import QArith_base.
Require Import Qcanon.
Require Import Qabs.
Require Import QArith.
Require Import Qring.
Require Import QOrderedType.
Require Import NArith.
Require Import BinNatDef.
Require Import Ndec.
Require Import Ngcd_def.
Require Import BinNat.
Require Import Nsqrt_def.
Require Import Ndiv_def.
Require Import Nnat.
Require Import Ndigits.
Require Import Ndist.
Require Import SetoidList.
Require Import ListTactics.
Require Import Streams.
Require Import List.
Require Import SetoidPermutation.
Require Import ListSet.
Require Import StreamMemo.
Require Import ClassicalDescription.
Require Import Eqdep_dec.
Require Import Decidable.
Require Import Diaconescu.
Require Import Epsilon.
Require Import Classical_Type.
Require Import SetIsType.
Require Import Classical_Pred_Set.
Require Import ProofIrrelevance.
Require Import FunctionalExtensionality.
Require Import Classical_Pred_Type.
Require Import EqdepFacts.
Require Import Eqdep.
Require Import ClassicalEpsilon.
Require Import JMeq.
Require Import Description.
Require Import Hurkens.
Require Import IndefiniteDescription.
Require Import Berardi.
Require Import Classical_Prop.
Require Import ConstructiveEpsilon.
Require Import ProofIrrelevanceFacts.
Require Import ClassicalChoice.
Require Import RelationalChoice.
Require Import ClassicalFacts.
Require Import ClassicalUniqueChoice.
Require Import Classical.
Require Import ChoiceFacts.
Require Import Finite_sets_facts.
Require Import Relations_2.
Require Import Ensembles.
Require Import Finite_sets.
Require Import Multiset.
Require Import Integers.
Require Import Classical_sets.
Require Import Powerset_Classical_facts.
Require Import Image.
Require Import Constructive_sets.
Require Import Permut.
Require Import Relations_1_facts.
Require Import Cpo.
Require Import Powerset_facts.
Require Import Relations_1.
Require Import Infinite_sets.
Require Import Powerset.
Require Import Partial_Order.
Require Import Relations_3_facts.
Require Import Relations_3.
Require Import Uniset.
Require Import Relations_2_facts.
Require Import String.
Require Import Ascii.
Require Import Cauchy_prod.
Require Import Ranalysis_reg.
Require Import Rpow_def.
Require Import RIneq.
Require Import Rgeom.
Require Import RiemannInt_SF.
Require Import Rbase.
Require Import Rseries.
Require Import Rcomplete.
Require Import Ratan.
Require Import Ranalysis.
Require Import Ranalysis2.
Require Import Rtrigo_reg.
Require Import SeqProp.
Require Import Rsigma.
Require Import Cos_rel.
Require Import Rtrigo1.
Require Import Exp_prop.
Require Import Ranalysis3.
Require Import Ranalysis1.
Require Import Rsqrt_def.
Require Import SeqSeries.
Require Import R_Ifp.
Require Import Rminmax.
Require Import Alembert.
Require Import Rfunctions.
Require Import RiemannInt.
Require Import Rlogic.
Require Import ArithProp.
Require Import Rtopology.
Require Import Machin.
Require Import SplitRmult.
Require Import Binomial.
Require Import Cos_plus.
Require Import Rpower.
Require Import Rbasic_fun.
Require Import NewtonInt.
Require Import Rtrigo_fun.
Require Import SplitAbsolu.
Require Import Reals.
Require Import Rtrigo_calc.
Require Import Rtrigo_def.
Require Import Sqrt_reg.
Require Import ROrderedType.
Require Import PartSum.
Require Import AltSeries.
Require Import R_sqr.
Require Import Ranalysis4.
Require Import Rtrigo_alt.
Require Import R_sqrt.
Require Import MVT.
Require Import DiscrR.
Require Import Integration.
Require Import PSeries_reg.
Require Import Rdefinitions.
Require Import LegacyRfield.
Require Import Rlimit.
Require Import Rprod.
Require Import Ranalysis5.
Require Import Rderiv.
Require Import Raxioms.
Require Import Rtrigo.
Require Import RList.
Require Import OrdersEx.
Require Import OrdersLists.
Require Import OrdersFacts.
Require Import DecidableTypeEx.
Require Import EqualitiesFacts.
Require Import OrderedTypeAlt.
Require Import OrdersAlt.
Require Import Equalities.
Require Import OrdersTac.
Require Import Orders.
Require Import DecidableType.
Require Import OrderedType.
Require Import OrderedTypeEx.
Require Import GenericMinMax.
Require Import Operators_Properties.
Require Import Relation_Definitions.
Require Import Relation_Operators.
Require Import Relations.
Require Import MSetFacts.
Require Import MSetProperties.
Require Import MSetGenTree.
Require Import MSetDecide.
Require Import MSetList.
Require Import MSetPositive.
Require Import MSetInterface.
Require Import MSetToFiniteSet.
Require Import MSetWeakList.
Require Import MSetAVL.
Require Import MSetEqProperties.
Require Import MSets.
Require Import MSetRBT.
Require Import VectorDef.
Require Import Fin.
Require Import VectorSpec.
Require Import Vector.
Require Import SetoidClass.
Require Import EquivDec.
Require Import SetoidTactics.
Require Import Init.
Require Import Morphisms_Prop.
Require Import SetoidDec.
Require Import Morphisms_Relations.
Require Import Morphisms.
Require Import Equivalence.
Require Import RelationClasses.
Require Import RelationPairs.

(* Loaded 8092 symbols (0.088 seconds) With optimized proof-general search *)
(* Loaded 8092 symbols (0.136 seconds) With plain proof-general search *)
(* Loaded 8092 symbols (0.155 seconds) With optimized proof-general search on battery *)

Lemma test : forall v, exists v', v' > v.
Proof.
  intros .
  exists (Qcplus v 1).

  setoid_rewrite Qclt_minus_iff.
  rewrite Qcplus_comm.
  rewrite Qcplus_assoc.
Qed.