#!/bin/sh

PATH_ELEMS="$(echo ${PATH} | tr -s ':' '\n')"

ORIG_GHC_PKG_BINARY=""

for PATH_ELEM in ${PATH_ELEMS}; do
    GHC_PKG_CANDIDATE="${PATH_ELEM}/ghc-pkg"
    if command -v "${GHC_PKG_CANDIDATE}" > /dev/null 2> /dev/null; then
        if [ "${0}" != "${GHC_PKG_CANDIDATE}" ]; then
            if [ -z "${ORIG_GHC_PKG_BINARY}" ]; then
                ORIG_GHC_PKG_BINARY="${GHC_PKG_CANDIDATE}"
            fi
        fi
    fi
done

if [ -z "${ORIG_GHC_PKG_BINARY}" ]; then
    echo "ghc-pkg wrapper: Couldn't find real ghc-pkg program"
    exit 1
fi

exec "$ORIG_GHC_PKG_BINARY" ${PACKAGE_DB_FOR_GHC_PKG} "$@"
