#!/usr/bin/env bash

# setup

REPO=$1
VERSION=$2
PACKAGE=org-trello
ARCHIVE=$PACKAGE-$VERSION.tar
CLEAN_INSTALL_FOLDER=$HOME/$PACKAGE-install-$REPO
EMACS_EXECUTE_FILE=test-install-file.el

# prepare

rm -rf $CLEAN_INSTALL_FOLDER
mkdir -p $CLEAN_INSTALL_FOLDER
cp $EMACS_EXECUTE_FILE $CLEAN_INSTALL_FOLDER
cp $ARCHIVE $CLEAN_INSTALL_FOLDER
cd $CLEAN_INSTALL_FOLDER

# execute

HOME=$CLEAN_INSTALL_FOLDER emacs --batch -l $EMACS_EXECUTE_FILE -- $REPO $ARCHIVE
