#+TITLE: Outshine Project Contributors
#+STARTUP: showeverything

* Adam Porter
  :PROPERTIES:
  :roles:    principal_developer maintainer
  :email:    <adam AT alphapapa DOT net>
  :FSF:      no
  :contributions: outshine.el outorg.el navi-mode.el
  :nontrivial: yes
  :END:

He assumed maintainership of the packages from Thorsten Jolitz in April 2017.

* Thorsten Jolitz
  :PROPERTIES:
  :roles:    original_author contributor former_maintainer
  :email:    <tjolitz AT gmail DOT com>
  :FSF:      yes
  :contributions: outshine.el outorg.el navi-mode.el
  :nontrivial: yes
  :END:

He had the initial idea, wrote most of the new code in outshine.el, as
well as the libraries outorg.el and navi-mode.el, and used to maintain
the whole project.

* Carsten Dominik 
  :PROPERTIES:
  :roles:    contributor
  :email:    <dominik AT uva DOT nl>
  :FSF:      yes
  :contributions: outshine.el
  :nontrivial: yes
  :END:

His library outline-magic.el was merged into outshine.el. 

#+begin_quote
;;; outline-magic.el --- outline mode extensions for Emacs

;; Copyright (C) 2002, 2013 Carsten Dominik, Thorsten Jolitz

;; Author: Carsten Dominik <dominik@science.uva.nl>
;; Maintainer: Thorsten Jolitz <tjolitz AT gmail DOT com>
;; Version: 0.9.1
;; Keywords: outlines

;; This file is not part of GNU Emacs.

;; GNU Emacs is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published
;; by the Free Software Foundation; either version 2, or (at your
;; option) any later version.
#+end_quote

* Per Abrahamsen
  :PROPERTIES:
  :roles:    contributor
  :email:    <abraham AT iesd DOT auc DOT dk>
  :FSF:      yes
  :contributions: outshine.el
  :nontrivial: yes
  :END:

His library [[https://stuff.mit.edu/afs/sipb/user/jtkohl/elisp/out-xtra.el][out-xtra.el]] was first modified and expanded into library
[[https://github.com/tj64/outxxtra][outxxtra]]. That library was then later-on merged into outshine.el.

#+begin_quote
;;; out-xtra.el --- Extra support for outline minor mode.

;; Copyright (C) 1993, 1994 Per Abrahamsen.
;; Copyright abandoned.  This file is donated to the public domain.

;; Author: Per Abrahamsen <abraham@iesd.auc.dk>
#+end_quote


* ???
  :PROPERTIES:
  :roles:    contributor
  :email:    ?
  :FSF:      ?
  :contributions: outshine.el
  :nontrivial: yes
  :END:

Library outline-mode-easy-bindings.el was extracted from the [[http://emacswiki.org/emacs/OutlineMinorMode][Emacs
Wiki]] and merged into outshine.el. Its author is unknown. 

#+begin_quote
;; [OBSOLETE FOR OUTSHINE.EL, BECAUSE ALL FUNCTIONS AND KEYBINDINGS FROM THIS
;; LIBRARY HAVE BEEN MERGED INTO OUTSHINE.EL]

;; outline-mode-easy-bindings.el (2010-08-15)
;; [...]
;; Copied from: http://emacswiki.org/emacs/OutlineMinorMode
#+end_quote

To avoid the legal issues introduced by this anonymous code, commit
b812d4550c1257cc48bd4296c323eba4fe5dd113 would have to been splitted
in parts and partly reversed. outline-mode-easy-bindings.el could then
be used as a soft (external) requirement of outshine.el.

* Jonathan Leech-Pepin
  :PROPERTIES:
  :roles:    contributor
  :email:    <jonathan.leechpepin AT gmail DOT com>
  :FSF:      yes
  :contributions: outorg-export.el
  :nontrivial: yes
  :END:

New library [[https://github.com/jleechpe/outorg-export][outorg-export]]. 

#+begin_quote
 ;;; outorg-export.el -- Automated exporting through org            
 ;; Author: Jonathan Leech-Pepin <jonathan.leechpepin AT gmail DOT  
 com                                                                
 ;; Version: 0.1                                                    
 ;; URL: https://github.com/jleechpe/outorg-export                  
 ;;;; MetaData                                                      
 ;; :PROPERTIES:                                                    
 ;; :copyright: Jonathan Leech-Pepin                                
 ;; :copyright-years: 2014+                                         
 ;; :version: 0.3                                                   
 ;; :licence: GPLv3 or later                                        
 ;; :licence-url: http://www.gnu.org/licenses/                      
 ;; :part-of-emacs: no                                              
 ;; :author: Jonathan Leech-Pepin                                   
 ;; :author_email: jonathan.leechpepin AT gmail DOT com             
 ;; :keywords: emacs org-mode export                                
 ;; :END:                                                           
#+end_quote

* Alexander Vorobiev
  :PROPERTIES:
  :roles:    contributor
  :email:  <alexander DOT vorobiev AT gmail DOT com>
  :FSF:      no
  :contributions: outshine.el
  :nontrivial: no
  :END:

Macro for conditional keybindings in outshine.el:

#+begin_quote
;; copied and adapted from Alexander Vorobiev
;; http://www.mail-archive.com/emacs-orgmode@gnu.org/msg70648.html
(defmacro outshine-define-key-with-fallback [...]
#+end_quote

Of course this macro isn't trivial from a programmers point of view,
its a rather sophisticated contribution. But since its just a few
lines of code, signing of FSF papers isn't necessary (its a trivial
contribution from a legal point of view).

* Fabrice Niessen
  :PROPERTIES:
  :roles:    contributor
  :email:  <fni AT mygooglest DOT com>
  :FSF:      yes
  :contributions: outshine.el
  :nontrivial: ?
  :END:

Modified snippets of his (old) [[http://www.mygooglest.com/fni/dot-emacs.html][dot-emacs]] made it into outshine.el.

* Jonas Bernoulli
  :PROPERTIES:
  :roles:    bug-reporter
  :email:  <jonas AT bernoul DOT li>
  :FSF:      yes
  :contributions: outshine.el
  :nontrivial: no
  :END:

Several bugs and issues reported.

* hanche
  :PROPERTIES:
  :roles:    contributor
  :github:   https://github.com/hanche
  :FSF:      no
  :contributions: outshine.el
  :nontrivial: no
  :END:

Bugfix.
