<!-- <h2><a name="about">About Proof General</a></h2> -->
<h2>The Proof General project</h2>
<p>
The Proof General project was initiated in 1994 (under the name of
"lego-mode") and coordinated until October 1998 by Thomas
Kleymann.  Since October 1998, David Aspinall has been in charge of
Proof General. 
<p>
<p>The project has benefited from funding by <a
href="http://www.dcs.ed.ac.uk/lfcs/research/logic_and_proof/attbpa.html">EPSRC</a>
and the <a
href="http://www.dcs.ed.ac.uk/lfcs/research/types_bra/index.html">EC</a>.
</p>

<p>
The generic base for Proof General was developed at the
<a href="http://www.dcs.ed.ac.uk/lfcs">LFCS</a> by Kleymann, Sequeira, 
Goguen and Aspinall (in order of appearance). 
It follows some of the ideas used in 
<a href="http://www.inria.fr/croap/">Project CROAP</a>.
</p>
<p>
The authors and current maintainers of the various instantiations of
Proof General are mentioned on the 
<?php link_root("main","front page.") ?>
</p>
<p>
For more on the history of the development of
Proof General, see the 
<?php htmlshow("ProofGeneral/doc/ProofGeneral_1.html#SEC3","manual preface.","","html") ?>
</p>

<h2>Contact information</h2>

<p>
Have you any questions, comments, or suggestions about Proof General?
<br>
Send us a message using <a href="feedback.phtml">this form</a>.
</p>

<p>
Discuss Proof General with other users and receive
announcements by joining our <a href="mailinglist.phtml">mailing
list</a>.
</p>



