<!-- <h2><a name="about">About Proof General</a></h2> -->
<h2>The Proof General project</h2>
<p>
The forefather of Proof General was LEGO mode, begun by Thomas
Kleymann in 1994 as an Emacs-based front end for LEGO similar to <a
href="http://www.dcs.ed.ac.uk/home/da/Isamode">Isamode</a>.  Later,
implementations of proof-by-pointing and script management were added,
and the code was made generic.  
</p>

<p>
This generic basis for Proof General was developed at the
<a href="http://www.dcs.ed.ac.uk/lfcs">LFCS</a> by Kleymann, Sequeira, 
Goguen and Aspinall (in order of appearance). 
Early on, Yves Bertot provided assistance, and Proof General follows 
some of the ideas used in <a href="http://www.inria.fr/croap/">Project CROAP</a>.

The authors and current maintainers of the various instantiations of
Proof General are mentioned on the 
<?php link_root("main","front page.") ?>
</p>
<p> 
The Proof General project was coordinated until October 1998 by Thomas
Kleymann, and since then by David Aspinall.
The project has benefited from
funding by <a
href="http://www.dcs.ed.ac.uk/lfcs/research/logic_and_proof/attbpa.html">EPSRC</a>
and the <a
href="http://www.dcs.ed.ac.uk/lfcs/research/types_bra/index.html">EC</a>.
</p>

<p>
David Aspinall designed the web pages and graphics for Proof General.
<br>
Check the <a href="gallery.phtml">gallery</a> for more publicity
pictures!
</p>
<p>
For more on the history of the development of
the Proof General program, see the 
<?php htmlshow("ProofGeneral/doc/ProofGeneral_1.html#SEC3","manual preface.","","html") ?>
</p>


<h2>Contact information</h2>

<p>
Have you any questions, comments, or suggestions about Proof General?
<br>
Send us a message using <a href="feedback.phtml">this form</a>.
</p>

<p>
Discuss Proof General with other users and receive
announcements by joining our <a href="mailinglist.phtml">mailing
list</a>.
</p>



