<?php  
  require('functions.php3');
  small_header("Proof General Development Release"); 
  ?>

<p>
<a href="#prerel">Here</a> is the latest pre-release of Proof General,
made available for those who wish to test the latest features or bug
fixes.  For developers, this release is also available as a 
<a href="#devel">complete CVS snapshot</a>.
</p>
<p>
Pre-releases of Proof General may be buggy as we add new features and
experiment with them.  Nonetheless, we welcome bug reports.  But
please make sure you are using the latest pre-release before
reporting problems.
</p>
<p>
Please <a href="register.phtml">register</a> if you haven't done so already.
</p>

<!-- WARNING!  Line below automatically edited by makefile. -->
<h2><a name="prerel">Pre-release: ProofGeneral-3.1pre000310</a></h2>
<!-- End Warning. -->

<p>
Check the 
<!-- WARNING!  Line below automatically edited by makefile. -->
<?php fileshow("ProofGeneral-3.1pre000310/CHANGES","CHANGES"); ?> file
<!-- End Warning. -->
for a summary of changes since the last stable version, and
the planned changes to come.
</p>
<ul>
<!-- WARNING!  Lines below automatically edited by makefile. -->
  <li> gzip'ed tar file: 
      <?php download_link("ProofGeneral-3.1pre000310.tar.gz") ?>
  </li>
  <li> Linux RPM package 
      <?php download_link("ProofGeneral-3.1pre000310-1.noarch.rpm") ?>
     <br>
     You probably don't need the 
    <?php download_link("ProofGeneral-3.1pre000310-1.src.rpm","source RPM") ?>.
  </li>
<!-- End Warning. -->
</ul>

For install instructions, see 
the <?php link_root("download#install",stable version download") ?>.

<p>
</p>
<p>
</p>


<!-- WARNING!  Line below automatically edited by makefile. -->
<h2><a name="devel">Complete Archive of ProofGeneral-3.1pre000310 for Developers</a></h2>
<!-- End Warning. -->

<p>
This archive is a snapshot from our CVS repository. 
</p>
<ul>
  <li> gzip'ed tar file: 
<!-- WARNING!  Line below automatically edited by makefile. -->
      <?php download_link("ProofGeneral-3.1pre000310-devel.tar.gz") ?>
<!-- End Warning. -->
  </li>
</ul>
<p>
What's the difference from the user's pre-release above?
The complete archive also includes:
</p>
<ul>
  <li> the low-level developer's todo files 
    (see <?php link_root("devel#lowleveltodo","the developers page") ?>)
   and the detailed
   <!-- WARNING!  Line below automatically edited by makefile. -->
   <?php fileshow("ProofGeneral-3.1pre000310/ChangeLog","ChangeLog"); ?>,
   <!-- End Warning. -->
 </li>
  <li> developer's Makefile used to generate documentation files 
       and the release itself,</li>
  <li> test files, </li>
  <li> image source files, </li>
  <li> the web pages, </li>
  <li> working instantiations of Proof General for new provers </li>
</ul>
<p>
Note: there are no pre-built documentation files in the developer's
release, because developers should have the right tools!
</p>
<p>
You probably <em>don't</em> need to download this if you're only
interested in hacking the Emacs lisp part of the program for
a prover that is currently supported.  
</p>

<?php
   click_to_go_back();
   footer();
?>
