<?php  
  require('functions.php3');
  small_header("Proof General Development"); 
  ?>

<p>
Here is the latest pre-release of Proof General.  For developers,
it is also available as a complete archive, including
forthcoming support for more proof assistants.
</p>
<p>
Pre-releases of Proof General may be buggy as we add new features and
experiment with them.  Nonetheless, we welcome bug reports.  But
please make sure you are using the current pre-release before
reporting problems.
</p>

<!-- WARNING!  Line below automatically edited by makefile. -->
<h2><a name="prerel">Pre-release: ProofGeneral-3.1pre000106</a></h2>
<!-- End Warning. -->

<p>
Check the 
<!-- WARNING!  Line below automatically edited by makefile. -->
<?php fileshow("ProofGeneral-3.1pre000106/CHANGES","CHANGES"); ?> file
<!-- End Warning. -->
for a summary of changes since the last stable version, and
the planned changes to come.
</p>
<ul>
<!-- WARNING!  Lines below automatically edited by makefile. -->
  <li> gzip'ed tar file: 
      <?php download_link("ProofGeneral-3.1pre000106.tar.gz") ?>
  </li>
  <li> Linux RPM package 
      <?php download_link("ProofGeneral-3.1pre000106-1.noarch.rpm") ?>
     <br>
     You probably don't need the 
    <?php download_link("ProofGeneral-3.1pre000106-1.src.rpm","source RPM") ?>.
  </li>
<!-- End Warning. -->
</ul>


<h2><a name="devel">Complete Archive of ProofGeneral-3.1pre000106</a></h2>

<p>
This archive is a snapshot from our CVS repository. 
</p>
<ul>
  <li> gzip'ed tar file: 
<!-- WARNING!  Line below automatically edited by makefile. -->
      <?php download_link("ProofGeneral-3.1pre000106-devel.tar.gz") ?>
<!-- End Warning. -->
  </li>
</ul>
<p>
What's the difference from the working version above?
The complete archive also includes:
</p>
<ul>
  <li> provisional instantiations of Proof General to new provers <br>
	(mentioned in the 
   <!-- WARNING!  Line below automatically edited by makefile. -->
  <?php fileshow("ProofGeneral-3.1pre000106/CHANGES","CHANGES"); ?> file),
   <!-- End Warning. -->
  </li>
  <li> the 
   <!-- WARNING!  Line below automatically edited by makefile. -->
   <?php fileshow("ProofGeneral-3.1pre000106/todo","low-level list of things to do"); ?>
   <!-- End Warning. -->
   and the detailed
   <!-- WARNING!  Line below automatically edited by makefile. -->
   <?php fileshow("ProofGeneral-3.1pre000106/ChangeLog","ChangeLog"); ?>,
   <!-- End Warning. -->
 </li>
  <li> developer's Makefile used to generate documentation files <br>
       and the release itself from our CVS repository,  </li>
  <li> some test files, </li>
  <li> sources for some of the images, 
  <li> the web pages.  
</ul>
<p>
Note: there are no pre-built documentation files in the developer's
release, because developers should have the right tools!
</p>
<p>
You probably <em>don't</em> need to download this if you're only
interested in hacking the Emacs lisp part of the program for
a prover that is currently supported.  But you may
still like to check the latest
<!-- WARNING!  Line below automatically edited by makefile. -->
<?php fileshow("ProofGeneral-3.1pre000106/todo","low-level to-do list"); ?>.
<!-- End Warning. -->
</p>

<p>
We have a mailing list for developers, at
<a href="mailto:proofgeneral-devel@dcs.ed.ac.uk">
<tt>proofgeneral-devel@dcs.ed.ac.uk</tt></a>.
<br>
To subscribe (or unsubscribe), send a message to 
<a href="mailto:majordomo@dcs.ed.ac.uk">
 <tt>majordomo@dcs.ed.ac.uk</tt>
</a>
with the words "<tt>subscribe proofgeneral-devel</tt>"
(or "<tt>unsubscribe proofgeneral-devel"</tt>) in the message body.
</p>

<p>
If you are interested in developing the core of Proof General,
we can make our CVS repository accessible to you.  Please 
<a href="feedback.phtml">ask</a>.
</p>

<?php
   click_to_go_back();
   footer();
?>
