<p>
Proof General follows an open development method.  
<br>
We welcome code contributions, suggestions, and bug reports, from all
users and hackers!
</p>

<ul>
<li>
Download the current <a href="develdownload.phtml">development release</a>.
</li>
</ul>
<ul>
<li>
Read the Proof General white paper (available soon)
</li>
</ul>
<ul>
<li>
Take a look at the Proof General <a href="projects.phtml">project proposals</a>.
</li>
</ul>
<ul>
<li>
<?php hlink("feedback.phtml","Send us a message ","Feedback form")?>
about any development issues.
</li>
</ul>

<h2><a name="develmail">Developers Mailing List</a></h2>

<p>
We have a mailing list for developers, at
<a href="mailto:proofgeneral-devel@dcs.ed.ac.uk">
<tt>proofgeneral-devel@dcs.ed.ac.uk</tt></a>.
<br>
To subscribe (or unsubscribe), send a message to 
<a href="mailto:majordomo@dcs.ed.ac.uk">
 <tt>majordomo@dcs.ed.ac.uk</tt>
</a>
with the words "<tt>subscribe proofgeneral-devel</tt>"
(or "<tt>unsubscribe proofgeneral-devel"</tt>) in the message body.
</p>

<p>
If you are interested in becoming an official developer of Proof
General, we can make our CVS repository accessible to you.  Please 
<a href="feedback.phtml">ask here</a>.
</p>

