<h2>Manual</h2>

<p>
Here is the  
<?php htmlshow("ProofGeneral/doc/ProofGeneral_toc.html","Proof General manual","Proof General Manual") ?> in HTML form, as included in the distribution.
<br>
For printing you can download the 
<?php download_link("ProofGeneral/doc/ProofGeneral.ps.gz", "gzipped ps file") ?> 
(recommended) or the 
<?php download_link("ProofGeneral/doc/ProofGeneral.pdf", "pdf file") ?>.
</p>

<p>
<i>Warning:</i> the links above are for the current
pre-release and may be updated from the documentation included
in the last stable release.
</p>

<p>
The manual (in HTML and Info formats), as well as other documentation,
is included in the <?php link_root("download","download.") ?> When
running Proof General the manual is available from the "Proof General"
menu.  It should also appear in the system Info pages.
</p>


<p>
You can discuss Proof General with other users and receive
announcements by joining our <a href="mailinglist.phtml">mailing
list</a>.
</p>

<hr>
<h2>References</h2>

<p> A technology overview of Proof General is given here:
</p>
<ul>
<li> <a href="http://www.dcs.ed.ac.uk/home/da">David Aspinall</a>.
    <a href="papers/pgoutline.ps.gz">Proof General: A Generic Tool for
     Proof Development</a>.
    <i>Demonstration at ETAPS 2000</i>. October 1999.
    Here are some <a href="papers/pgtalk">draft slides</a> 
    for the demonstration  
     (<a href="mailto:da@dcs.ed.ac.uk">comments</a> welcome).
</li>
</ul>
<p> Proof General supports Script Management as documented in:
</p>
<ul>
  <li> <a
      href="http://www.inria.fr/croap/personnel/Yves.Bertot/me.html">Yves
      Bertot</a> and <a
      href="http://www.inria.fr/croap/personnel/Laurent.Thery/me.html">Laurent
      Th&eacute;ry</a>.  <a
      href="ftp://babar.inria.fr/pub/croap/bertot/jsymcomp.ps">A
      generic approach to building user interfaces for theorem
      provers</a>.  
      <I>Journal of Symbolic Computation</I>, 25(7), pp. 161-194, February 1998.
  </li>
 </ul>
 <p>
 It has support for Proof by Pointing, as documented in:
 </p>
 <ul>
  <li> <A
      HREF="http://www.inria.fr/croap/personnel/Yves.Bertot/me.html">Yves
      Bertot</A>, <A HREF="http://www.dcs.ed.ac.uk/home/tms">
      Thomas Kleymann-Schreiber</A> and <A
      HREF="http://www.dcs.ed.ac.uk/home/djs">Dilip Sequeira</a>.
    <I>Implementing Proof by Pointing without a Structure Editor</I>.
    LFCS Technical Report <A
    HREF="http://www.dcs.ed.ac.uk/lfcsreps/EXPORT/97/ECS-LFCS-97-368/index.html">ECS-LFCS-97-368</a>.
    Also published as Rapport de recherche de l'INRIA
    <A HREF="http://www.inria.fr/Unites/SOPHIA-eng.html"> Sophia
      Antipolis</a> <A
      HREF="http://www.inria.fr/RRRT/RR-3286.html">RR-3286</a>
  </li>
</ul>

