<h2>Please register</h2>
<p>
Before downloading Proof General, <i>please</i>
<a href="register.phtml">register</a>.
It only takes a moment.
<br>
The information collected will be used to help a case for
support for Proof General, and nothing else.
It is likely that development of Proof General will 
<i>finish very soon</i> unless we can find new
resources.
If you have already registered you do not need to do so again.
</p>

<p>
You may like to consider joining the 
Proof General
<a href="mailinglist.phtml">mailing list</a>.
</p>

<p>
Developers and beta-testers may like to download
a <a href="devel.phtml">development release</a>
of Proof General.
</p>

<p>
If you are using an older version of a proof assistant,
you may wish to check the 
<a href="oldrel.phtml">previous releases</a> of Proof General.
</p>
<hr>

<h2><a name="stable">
    Proof General Version 2.1, released 24th August 1999
    </a>
</h2>

<p>
This version of Proof General has been tested
with XEmacs 20.4, XEmacs 21 and FSF Emacs 20.3.<br>
It supports Coq version 6.3, LEGO version 1.3.1 and
some pre-release versions of Isabelle version 99.
<p>
Check the <?php fileshow("ProofGeneral-2.1/CHANGES","CHANGES"); ?> file
for a summary of changes since version 2.0.
<br>
Proof General is available in two formats:
</p>
<ul>
  <li> gzip'ed tar file: 
      <?php download_link("ProofGeneral-2.1.tar.gz") ?>
  </li>
 <li> Linux RPM package:
      <?php download_link("ProofGeneral-2.1-1.noarch.rpm") ?>
     <br>
     The source RPM is 
      <?php download_link("ProofGeneral-2.1-1.noarch.rpm","here") ?>.
 </li>
</ul>
<p>
Both the tarball and the RPM package include the generic elisp
code, <br>
code for LEGO, Coq, and Isabelle, installation instructions
and documentation. 
</p>

<h3> Easy installation! </h3> 
<p>
To use Proof General, simply unpack the sources with 
</p>
 <blockquote>
   <tt>tar -xpzf ProofGeneral-2.1.tar.gz</tt>
 </blockquote>
<p>
(use <tt>gunzip</tt> first in place of -z if you don't have GNU tar),<br>
and then add this one line to your .emacs file:
</p>
 <blockquote>
  <tt> (load-file "<var>directory</var>/generic/proof-site.el")</tt>
 </blockquote>
<p>
Where <var>directory</var> is the directory in which you unpacked
the sources.  
<br>
If you use the RPM package, <var>directory</var> is
<tt>/usr/share/emacs/ProofGeneral</tt>
</p>
<p>
Further customization is possible via the Customize menus in
Emacs.  
<br>
See the <?php fileshow("ProofGeneral/INSTALL","INSTALL")?> 
file in the distribution for more details.
</p>
<p>
Please <a href="mailto:proofgen@dcs.ed.ac.uk">send us</a>
any problems, suggestions, or patches. 
</p>



