<?php  
  require('functions.php3');
  small_header("Proof General Gallery"); 
  ?>

<blockquote>
<p>
Here are some publicity pictures for Proof General.  They were created
by David Aspinall in his spare time, using the excellent freeware
programs <a href="http://www.gimp.org">GIMP</a> and <a
href="http://www.blender.nl">Blender</a>.  The General himself is
based on a commercial mesh by 
<a href="http://www.viewpoint.com">Viewpoint</a>.
</p>
<p>
Click on a thumbnail to see a full-size images.  All full-size images
are 720x990 pixel JPGs (a nice size to print at 180dpi on A5 paper).
Please download and print for your own use!  
</p>
Please <a href="feedback.phtml">contact us</a> with comments or
suggestions, or if you would like a copy of one of the images
in another size or format.
</p>
<p>
Copyright for the images is held by LFCS, University of Edinburgh.
Please do not publish the images or incorporate them into other
work without our permission.
</p>
</blockquote>

<!-- todo: php3 this -->
<table width="80%">
<tr>
<td width="200">
<a href="images/portrait.jpg">
<img src="images/portrait-thumb.jpg" alt="Portrait" width=150 height=206 border=0>
</a>
</td>
<td>
<p>
Proof General portrait <br>
This is the Proof General logo, 
with the home page URL at the bottom. <br>
A nice poster for your wall or door. <br>
</p>
</tr>
<tr>
<td>
<a href="images/whip.jpg">
<img src="images/whip-thumb.jpg" alt="New recruit" width=150 height=206 border=0>
</a>
</td>
<td>
<p>
New Recruits Wanted  <br>
This is a request for help with the Proof General
project. <br>
Please <a href="feedback.phtml">sign up here</a>!
</p>
</tr>
<tr>
<td>
<a href="images/whole-man.jpg">
<img src="images/whole-man-thumb.jpg" alt="Whole man" width=150 height=206 border=0>
</a>
</td>
<td>
<p>
Scary boots!  <br>
This is a full-length shot of Proof General,
again with the home page at the bottom.
</p>
</tr>
</table>

<?php
   click_to_go_back();
   footer();
?>
