<head>
    <title>Proof General --- Organize your Proofs!</title>
    <meta name="author" content="David Aspinall <da@dcs.ed.ac.uk>">
    <meta name="keywords" content="Isabelle, LEGO, Coq, Emacs, XEmacs, 
      Interface, Theorem Prover, GUI, David Aspinall">
    <meta name="description" content="Proof General is an Emacs based 
      generic interface for theorem provers">
<?php
/* Did have linked style sheet, with:
 *   <link rel="stylesheet" href="proofgen.css" type="text/css">
 * Instead, its embedded it to save another server access.
 */
 print "<style type=\"text/css\">\n<!--";
 include("proofgen.css");
 print "-->\n</style>\n";
?>
</head>
