<p>
Here are some links to related things.  
<br>
If you have any suggestions 
for links to include here, or find broken links, please
<?php hlink("feedback.phtml","contact us","Feedback form")?>.
</p>

<ul>
<li><a href="http://www.dcs.ed.ac.uk/home/da/Isamode">Isamode</a>
  is an XEmacs front-end for Isabelle.  It has a different
  feature collection compared with Proof General:
  script management is not supported, but there are extensive
  menus and shortcuts provided for common Isabelle
  commands.
</li>
</ul>
