<!-- <?php  print $separator; ?> -->
<!-- <a href="#what">What</a>  -->
<!-- <?php  print $separator; ?> -->
<!-- <a href="#why">Why</a>  -->
<!-- <?php  print $separator; ?> -->
<!-- <a href="#about">About</a>  -->
<!-- </br> -->


<!-- <h2><a name="what">What is Proof General?</a></h2> -->

<p>
<b>Proof General</b> is a generic interface for proof assistants, 
based on Emacs.<br>
It has been developed at the
<a href="http://www.dcs.ed.ac.uk/lfcs">LFCS</a>
in the <a href="http://www.ed.ac.uk/">University of Edinburgh</a>.
</p>
<p>
Proof General 
works best under 
<a href="http://www.xemacs.org/">XEmacs</a>, but can also be used with 
<a href="http://www.gnu.org/software/emacs/">FSF GNU Emacs</a>.
<br>
You need a 20.X (or later) version in either case.
</p>

<p>
Proof General is ready-customized for several proof assistants:
</p>

<table width="90%">
  <tr>
    <td align="center">
       <?php hlink("http://pauillac.inria.fr/coq/assis-eng.html",
		   "<img src=\"images/coq-badge.gif\" width=110 height=35 border=0 alt=\"Coq badge\">","The Coq Home Page") ?>
      </td>
    <td>
     <b> Coq Proof General </b> for 
       <?php hlink("http://pauillac.inria.fr/coq/assis-eng.html",
		   "Coq","The Coq Home Page") ?>
       version 6.2
       <br>
	<div style="font-size: smaller">
         First crafted by 
         <a href="http://www.dcs.ed.ac.uk/~hhg">Healfdene Goguen</a>. 
         <br>
	 Currently maintained and developed by Patrick Loiseleur.
        </div>
    </td>
 </tr>
 <tr>
    <td align="center">
       <?php hlink("http://www.dcs.ed.ac.uk/home/lego",
       "<img src=\"images/lego-badge.gif\" width=123 height=33 border=0 alt=\"LEGO badge\">",
       "The LEGO Home Page") ?>
   </td>
    <td><b>LEGO Proof General</b>
       <?php hlink("http://www.dcs.ed.ac.uk/home/lego",
		   "LEGO","The LEGO Home Page") ?>
       version 1.3.1
       <br>
       <div style="font-size: smaller">
       First crafted by <a href="http://www.dcs.ed.ac.uk/~tms">Thomas Kleymann</a>
       and
        <a href="http://www.dcs.ed.ac.uk/~djs">Dilip Sequeira</a>.
       <br>
       Maintained by <a href="http://www.dur.ac.uk/~dcs1pcc/">Paul
       Callaghan</a>.
       </div>
    </td>
 </tr>
 <tr>
   <td align="center">
       <?php hlink("http://www.cl.cam.ac.uk/Research/HVG/Isabelle/",
      "<img src=\"images/isabelle-badge.gif\" width=128 height=37 border=0 alt=\"Isabelle badge\">",
      "The Isabelle Home Page"); ?>
   </td>
   <td><b> Isabelle Proof General </b> for
       <?php hlink("http://www.cl.cam.ac.uk/Research/HVG/Isabelle/",
		    "Isabelle", "The Isabelle Home Page"); ?>
       version 99
      <br>
       <div style="font-size: smaller">
       Crafted and maintained by 
      <a href="http://www.dcs.ed.ac.uk/~da">David Aspinall</a>.
      <br>
      Support for
      <a href="http://isabelle.in.tum.de/Isar/">Isabelle/Isar</a>
      is provided by
      <a href="http://www.in.tum.de/~wenzelm/">Markus Wenzel</a>.
       </div>
   </td>
 </tr>
</table>

<p>
To see what Proof General looks like in use, have a look at this
<a href="screenshot.phtml">screenshot</a>.
</p>


<p>
You can download Proof General 
<?php link_root("download","here") ?> or contact the developers 
<?php hlink("feedback.phtml","here","Feedback form")?>.
</p>

