<p>
<!-- da: Put this line in instead if you're not me -->
<!-- <i>(News items entered by <a href="http://www.dcs.ed.ac.uk/~da">David Aspinall</a> -->
<!--     unless noted.)</i> -->
<i>(News items by <a href="http://www.dcs.ed.ac.uk/~da">David Aspinall</a>)</i>
</p>

<ul>
<li><b>26th November 1999</b><br>
<p>
Proof General 3.0 is released!
</p>
</ul>
<p>
<i>(Click <a href="oldnews.phtml">here</a> for old news)</i>
</p>



