<p>
<!-- da: Put this line in instead if you're not me -->
<!-- <i>(News items entered by <a href="http://www.dcs.ed.ac.uk/~da">David Aspinall</a> -->
<!--     unless noted.)</i> -->
<i>News items by <a href="http://zermelo.dcs.ed.ac.uk/~da">David Aspinall</a>.</i>
</p>

<ul>
<li><b>28th Aug 2000</b>
<p>
We're starting the testing phase for Proof General 3.2.  
It has several new features and improvements.
Please try out the <a href="develdownload.phtml">pre-release</a>
version, and report any problems to us.  Your
feedback is very important because we have no resources available for
serious compatibility testing ourselves.
</p>
<p>
We hope to release 3.2 by the end of September.
</p>
</li>
</ul>
<p>
<i>Click <a href="oldnews.phtml">here</a> for old news.</i>
</p>



