<ul>
<li><b>Very soon now</b><br>
<!-- 23rd August 1999  -->
 <p>
 Proof General version 2.1 is released.
 <br>
  Check the <?php fileshow("ProofGeneral-2.1/CHANGES","CHANGES"); ?> file
  for a summary of changes since Proof General 2.0.
 </p>
 <p>
  It is recommended that all users upgrade except
  those still using Isabelle 98-1.  
  <br> 
  Proof General 2.1 supports only the 99 version of Isabelle.
 </p>
</li>

<li><b>24th June 1999</b><br>
  <p>
  New Proof General web pages go live!
  </p>
  <p>
  The general is now more serious looking.
  Appropriate, because there are some serious improvements 
  in the pipeline...
  Before that, we will release Proof General 2.1,
  mainly a bug-fix improvement of 2.0.
  </p>
  <p>
  Please explore the new web pages and report any problems 
  or suggestions to <?php pg_email() ?>.
  Please also try out the latest pre-release of Proof General,
  this is the final chance to get fixes and tweaks
  sorted before 2.1.
  </p>
</li>

<li><b>11th May 1999</b><br>
  <p>A new instantiation of Proof General has been added by
  <a href="http://www.dur.ac.uk/~dcs1pcc/">Paul Callaghan</a>
  for 
  <a href="http://www.dur.ac.uk/~dcs7ttg/plastic.html">Plastic</a>,
  a new proof assistant based on
  Luo's Typed Logical Framework and
  implemented in Haskell. 
  </p>
</li>

<li><b>16th April 1999</b><br>
  <p>A new instantiation of Proof General has been added by
  <a href="http://www.in.tum.de/~wenzelm/">Markus Wenzel</a>
  for <a href="http://isabelle.in.tum.de/Isar/">Isabelle/Isar</a>,
  a new proof language for Isabelle to be included with Isabelle 99. 
  </p>
</li>

</ul>



