<?php  
  require('functions.php3');
  small_header("Proof General Old News"); 
  ?>
<ul>
<li><b>17th November 1999</b><br>
<p>
Proof General 3.0 is currently in final testing, and will be released
in a small number of days.  Please help me with this by testing the
current <a href="devel.phtml">pre-release</a>, so I can iron out as
many bugs as possible before making the release.  It's very easy to
install or upgrade Proof General, so it shouldn't be much effort to
test it quickly.  Particularly if you're already running an earlier
version.
</p>
<li><b>16th November 1999</b><br>
<p>
New!  With Proof General 3.0, adapting to a new prover is easier
than ever before!
It includes an 
 <?php fileshow("ProofGeneral/demoisa/demoisa-easy.el", "example instance ");?>
of Proof General for Isabelle, which 
configures the main core of the interface with less than 30 lines of
code.  Not bad for getting about 4000 lines worth of code in benefit!
</p>
<li><b>9th November 1999</b><br>
<p>
Isabelle 99 was released last week, and Proof General 3.0 should
be ready for release in the next week or so.  In
the meantime, please use the current 
<a href="devel.phtml">pre-release</a>
for Isabelle 99.
</p>
<p>
Some recent changes have been made to the support for
<a href="http://www.fmi.uni-passau.de/~wedler/x-symbol/">X-Symbol</a>,
so that it is easier to turn on and off, and support is now
properly generic.  At the moment only Isabelle has 
support implemented.
</p>
<li><b>21st October 1999</b><br>
 <p>
 See what Proof General 3.0 will look like!
 The <a href="screenshot.phtml">screenshot</a> has been updated.
 </p>
<li><b>14th October 1999</b><br>
 <p>
 The next version of Proof General will be 3.0.
 </p>
 <p>
 There have been significant changes to the core of 
 Proof General and many improvements in the code.
 Extra features have been added, and the ones already
 there improved upon.  Usability has been a particular
 focus.  Adding new provers has been made easier.
 Installation will be made even easier.
 All of these changes warrant moving to a major release!
 </p>
 <p>
 Version 3.0 is planned for release in November.
 Please test a Version 3.0 pre-release if you can
 and report any problems.
 </p>
<li><b>12th October 1999</b><br>
 <p>
 I'm very grateful to 
 <a href="mailto:courtieu@lri.fr">Pierre Courtieu &lt;courtieu@lri.fr&gt;</a>
 for offering to help work on Coq Proof General.
 <br>
 If anyone else in the Coq community would like to assist, please
 offer still, 
 there is plenty to do to add: better recognition of proof scripts,
 multiple file management, proof by pointing, etc...
 </p>
<li><b>1st October 1999</b><br>
 <p>
 Recently there has been a flurry of work on the next version of Proof
 General.  It has quite a number of improvements (see the <?php
 fileshow("ProofGeneral/CHANGES","CHANGES"); ?> file), made by myself
 and Markus Wenzel.  <br> The next version is aimed to coincide 
 roughly with the release of Isabelle 99.
 </p>
 <p>
 At the moment we <b>urgently need</b> somebody from the Coq world to
 maintain and improve Coq Proof General, since Patrick Loiseleur 
 can no longer work on it.  
 Support from the Coq community is vital for Proof General to
 be a useful tool there. <a href="feedback.phtml">Please offer to help</a>, 
 it needn't be a heavy commitment.
 </p>
<li><b>13th September 1999</b><br>
 <p>
 I've just returned from the 
 <a href="http://www-sop.inria.fr/types-project/types-sum-school.html">Types Summer School, Giens, France</a>
 where Proof General was used for a class of
 about 50 students who were learning
 Coq, Isabelle, and LEGO.  I received
 many useful comments and feedback,
 which will be
 used to improve the next version.
 Thanks to everyone who gave suggestions and bug reports
 to me, including: 
 Michael Abbott,
 Bernd Grobauer,
 Sebastian Skalberg,
 Thierry Massart,
 Darmalingum Muthiayen.
 <br>
 </p>
<li><b>27th August 1999</b><br>
 <p>
 Print pictures from the new 
 <a href="gallery.phtml">gallery</a>
 of publicity shots of Proof General!
 </p>
<li><b>24th August 1999</b><br>
 <p>
 Proof General version 2.1 is released.
 <br>
  Check the <?php fileshow("ProofGeneral-2.1/CHANGES","CHANGES"); ?> file
  for a summary of changes since Proof General 2.0.
 </p>
 <p>
  It is recommended that all users upgrade except
  those still using Isabelle 98-1.  
  <br> 
  Proof General 2.1 supports only the 99 version of Isabelle.
 </p>
</li>

<li><b>24th June 1999</b><br>
  <p>
  New Proof General web pages go live!
  </p>
  <p>
  The general is now more serious looking.
  Appropriate, because there are some serious improvements 
  in the pipeline...
  Before that, we will release Proof General 2.1,
  mainly a bug-fix improvement of 2.0.
  </p>
  <p>
  Please explore the new web pages and report any problems 
  or suggestions to <?php mlink($project_email); ?>.
  Please also try out the latest pre-release of Proof General,
  this is the final chance to get fixes and tweaks
  sorted before 2.1.
  </p>
</li>

<li><b>11th May 1999</b><br>
  <p>A new instantiation of Proof General has been added by
  <a href="http://www.dur.ac.uk/~dcs1pcc/">Paul Callaghan</a>
  for 
  <a href="http://www.dur.ac.uk/~dcs7ttg/plastic.html">Plastic</a>,
  a new proof assistant based on
  Luo's Typed Logical Framework and
  implemented in Haskell. 
  </p>
</li>

<li><b>16th April 1999</b><br>
  <p>A new instantiation of Proof General has been added by
  <a href="http://www.in.tum.de/~wenzelm/">Markus Wenzel</a>
  for <a href="http://isabelle.in.tum.de/Isar/">Isabelle/Isar</a>,
  a new proof language for Isabelle to be included with Isabelle 99. 
  </p>
</li>
</ul>
<p>
<i>News items by <a href="http://www.dcs.ed.ac.uk/~da">David Aspinall</a>.</i>
</p>


<?php
   click_to_go_back();
   footer();
?>
