<?php  
  require('functions.php3');
  small_header("Screenshot"); 
?>
<p>
Below is a picture of Isabelle Proof General running inside XEmacs,
replaying a simple proof.
</p>
<p>
The top half of the window displays the proof script. 
</p>
<p>
The blue highlighted region is the part of the script which has been
sent to the proof process so far.  It cannot be edited.
</p>
<p>
The bottom half of the window displays the output from Isabelle
at each stage of the proof.
</p>
<img src="images/IsaPGscreen.jpg" ALT="Isabelle Proof General screenshot">

<?php  
   click_to_go_back();
   footer();
?>
