<?php  
  require('functions.php3');
  small_header("Screenshot"); 
?>
<p>
Below is a picture of Isabelle Proof General 3.0 running inside XEmacs.
<br>
We are replaying a proof in Isar, Isabelle's new proof language
developed by Markus Wenzel.
</p>
<p>
The top half of the window displays the proof script. 
</p>
<p>
The blue highlighted region is the part of the script which has been
sent to the proof process so far.  It cannot be edited.
</p>
<p>
The bottom half of the window displays the output from Isabelle
at each stage of the proof.
</p>
<img src="images/pg-isar-screenshot.png" ALT="Isabelle Proof General screenshot [png support needed]">
<?php  
   click_to_go_back();
   footer();
?>
