#!/bin/sh

set -e
cd "$(dirname "$0")/.."

find . -name '*.elc' -delete
cask exec "${EMACS:-emacs}" -batch \
     -L . \
     --eval "(setq byte-compile-warnings '(not cl-functions))" \
     -f batch-byte-compile $(ls *.el|grep -v -- -pkg.el)
