#!/bin/bash
#
# Example publishing script for johnw's configuration

style=$(echo $1 | sed 's/^--//')
shift
emacs -q -batch -L $(dirname $0) \
    -l muse-build.el -l muse-johnw.el \
    -f muse-batch-publish-files $style --output-dir=. "$@"
