pref("extensions.mozrepl.initUrl", "");
pref("extensions.mozrepl.autoStart", false);
pref("extensions.mozrepl.port", 4242);
pref("extensions.mozrepl.loopbackOnly", true);
pref("extensions.mozrepl.version", "");
pref("extensions.mozrepl.defaultInteractor", "javascript");
pref("extensions.mozrepl.interactor.javascript.printWelcome", true);
pref("extensions.mozrepl.startingContext", "");
pref("extensions.mozrepl.noLog", false);
