;;; -*- coding: utf-8; -*-
;; isar-unicode-tokens.el --- Tokens for Unicode Tokens package
;;
;; Copyright(C) 2008 David Aspinall / LFCS Edinburgh
;; Author:    David Aspinall <David.Aspinall@ed.ac.uk>
;;
;; This file is loaded by `proof-unicode-tokens.el'.
;;
;; It sets the variables defined at the top of unicode-tokens.el,
;; unicode-tokens-<foo> is set from isar-<foo>.  See the corresponding
;; variable for documentation.
;;

(defconst isar-token-format "\\<%s>")
(defconst isar-charref-format "\\<#x%x>")
(defconst isar-token-prefix "\\<")
(defconst isar-token-suffix ">")
(defconst isar-token-match "\\\\<\\([a-zA-Z0-9]+\\)")
(defconst isar-control-token-match "\\\\<^\\([a-zA-Z0-9]+\\)>")
(defconst isar-control-token-format "\\<^%s>")
(defconst isar-hexcode-match "\\\\<\\(#[xX][0-9A-Fa-f]+\\)")
(defconst isar-next-character-regexp "\\\\<#[xX][0-9A-Fa-f]+>\\|.")

(defcustom isar-token-name-alist
  '(; token name, unicode char sequence
    ;; Based on isabellesym.sty,v 1.45 2006/01/05

    ;; Bold numerals: here subscripts 
    ("one" . "₁")
    ("two" . "₂")
    ("three" . "₃")
    ("four" . "₄")
    ("five" . "₅")
    ("six" . "₆")
    ("seven" . "₇")
    ("eight" . "₈")
    ("nine" . "₉")
    ;; Mathcal 
;;     ("A" . "")
;;     ("B" . "")
;;     ("C" . "")
;;     ("D" . "")
;;     ("E" . "")
;;     ("F" . "")
;;     ("G" . "")
;;     ("H" . "")
;;     ("I" . "")
;;     ("J" . "")
;;     ("K" . "")
;;     ("L" . "")
;;     ("M" . "")
;;     ("N" . "")
;;     ("O" . "")
;;     ("P" . "")
;;     ("Q" . "")
;;     ("R" . "")
;;     ("S" . "")
;;     ("T" . "")
;;     ("U" . "")
;;     ("V" . "")
;;     ("W" . "")
;;     ("X" . "")
;;     ("Y" . "")
;;     ("Z" . "")
    ;; Math roman
;;     ("a" . "")
;;     ("b" . "")
;;     ("c" . "")
;;     ("d" . "")
;;     ("e" . "")
;;     ("f" . "")
;;     ("g" . "")
;;     ("h" . "")
;;     ("i" . "")
;;     ("j" . "")
;;     ("k" . "")
;;     ("l" . "")
;;     ("m" . "")
;;     ("n" . "")
;;     ("o" . "")
;;     ("p" . "")
;;     ("q" . "")
;;     ("r" . "")
;;     ("s" . "")
;;     ("t" . "")
;;     ("u" . "")
;;     ("v" . "")
;;     ("w" . "")
;;     ("x" . "")
;;     ("y" . "")
;;     ("z" . "")
    ;; Fraktur
;;     ("AA" . "")
;;     ("BB" . "")
;;     ("CC" . "")
;;     ("DD" . "")
;;     ("EE" . "")
;;     ("FF" . "")
;;     ("GG" . "")
;;     ("HH" . "")
;;     ("II" . "")
;;     ("JJ" . "")
;;     ("KK" . "")
;;     ("LL" . "")
;;     ("MM" . "")
;;     ("NN" . "")
;;     ("OO" . "")
;;     ("PP" . "")
;;     ("QQ" . "")
;;     ("RR" . "")
;;     ("SS" . "")
;;     ("TT" . "")
;;     ("UU" . "")
;;     ("VV" . "")
;;     ("WW" . "")
;;     ("XX" . "")
;;     ("YY" . "")
;;     ("ZZ" . "")
;;     ("aa" . "")
;;     ("bb" . "")
;;     ("cc" . "")
;;     ("dd" . "")
;;     ("ee" . "")
;;     ("ff" . "")
;;     ("gg" . "")
;;     ("hh" . "")
;;     ("ii" . "")
;;     ("jj" . "")
;;     ("kk" . "")
;;     ("ll" . "")
;;     ("mm" . "")
;;     ("nn" . "")
;;     ("oo" . "")
;;     ("pp" . "")
;;     ("qq" . "")
;;     ("rr" . "")
;;     ("ss" . "")
;;     ("tt" . "")
;;     ("uu" . "")
;;     ("vv" . "")
;;     ("ww" . "")
;;     ("xx" . "")
;;     ("yy" . "")
;;     ("zz" . "")
    ("alpha" . "α")
    ("beta" . "β")
    ("gamma" . "γ")
    ("delta" . "δ")
    ("epsilon" . "ε") ; actually varepsilon (some is epsilon)
    ("zeta" . "ζ")
    ("eta" . "η")
    ("theta" . "θ")
    ("iota" . "ι")
    ("kappa" . "κ")
    ("lambda" . "λ")
    ("mu" . "μ")
    ("nu" . "ν")
    ("xi" . "ξ")
    ("pi" . "π")
    ("rho" . "ρ")
    ("sigma" . "σ")
    ("tau" . "τ")
    ("upsilon" . "υ")
    ("phi" . "ϕ")
    ("chi" . "χ")
    ("psi" . "ψ")
    ("omega" . "ω")
    ("Gamma" . "Γ")
    ("Delta" . "Δ")
    ("Theta" . "Θ")
    ("Lambda" . "Λ")
    ("Xi" . "Ξ")
    ("Pi" . "Π")
    ("Sigma" . "Σ")
    ("Upsilon" . "Υ")
    ("Phi" . "Φ")
    ("Psi" . "Ψ")
    ("Omega" . "Ω")
;;  ("bool" . "")
    ("complex" . "ℂ")
    ("nat" . "ℕ")
    ("rat" . "ℚ")
    ("real" . "ℝ")
    ("int" . "ℤ")
    ;; Arrows
    ("leftarrow" . "←")
    ("rightarrow" . "→")
    ("Leftarrow" . "⇐")
    ("Rightarrow" . "⇒")
    ("leftrightarrow" . "↔")
    ("Leftrightarrow" . "⇔")
    ("mapsto" . "↦")
    ;; Real long symbols, may work in some places
    ("longleftarrow" . "⟵")
    ("Longleftarrow" . "⟸")
    ("longrightarrow" . "⟶")
    ("Longrightarrow" . "⟹")
    ("longleftrightarrow" . "⟷")
    ("Longleftrightarrow" . "⟺")
    ("longmapsto" . "⟼")
    ;; Faked long symbols, for use otherwise:
;;;     ("longleftarrow" . "←–")
;;;     ("Longleftarrow" . "⇐–")
;;;     ("longrightarrow" . "–→")
;;;     ("Longrightarrow" . "–⇒")
;;;     ("longleftrightarrow" . "←→")
;;;     ("Longleftrightarrow" . "⇐⇒")
;;;     ("longmapsto" . "❘→")
    ("midarrow" . "–") ; #x002013 en dash
    ("Midarrow" . "‗") ; #x002017 double low line (not mid)
    ("hookleftarrow" . "↩")
    ("hookrightarrow" . "↪")
    ("leftharpoondown" . "↽")
    ("rightharpoondown" . "⇁")
    ("leftharpoonup" . "↼")
    ("rightharpoonup" . "⇀")
    ("rightleftharpoons" . "⇌")
    ("leadsto" . "↝")
    ("downharpoonleft" . "⇃")
    ("downharpoonright" . "⇂")
    ("upharpoonleft" . "↿")
    ;; ("upharpoonright" . "↾") overlaps restriction
    ("restriction" . "↾") ;; 
    ("Colon" . "∷")
    ("up" . "↑")
    ("Up" . "⇑")
    ("down" . "↓")
    ("Down" . "⇓")
    ("updown" . "↕")
    ("Updown" . "⇕")
    ("langle" . "⟪")
    ("rangle" . "⟫")
    ("lceil" . "⌈")
    ("rceil" . "⌉")
    ("lfloor" . "⌊")
    ("rfloor" . "⌋")
    ("lparr" . "⦇")
    ("rparr" . "⦈")
    ("lbrakk" . "⟦")
    ("rbrakk" . "⟧")
;;     ("lbrace" . "") TODO
;;    ("rbrace" . "")
    ("guillemotleft" . "«")
    ("guillemotright" . "»")
    ("bottom" . "⊥")
    ("top" . "⊤")
    ("and" . "∧")
    ("And" . "⋀")
    ("or" . "∨")
    ("Or" . "⋁")
    ("forall" . "∀")
    ("exists" . "∃")
    ("nexists" . "∄")
    ("not" . "¬")
    ("box" . "□")
    ("diamond" . "◇")
    ("turnstile" . "⊢")
    ("Turnstile" . "⊨")
    ("tturnstile" . "⊩")
    ("TTurnstile" . "⊫")
    ("stileturn" . "⊣")
    ("surd" . "√")
    ("le" . "≤")
    ("ge" . "≥")
    ("lless" . "≪")
    ("ggreater" . "≫")
    ("lesssim" . "⪍")
    ("greatersim" . "⪎")
    ("lessapprox" . "⪅")
    ("greaterapprox" . "⪆")
    ("in" . "∈")
    ("notin" . "∉")
    ("subset" . "⊂")
    ("supset" . "⊃")
    ("subseteq" . "⊆")
    ("supseteq" . "⊇")    
    ("sqsubset" . "⊏")
    ("sqsupset" . "⊐")
    ("sqsubseteq" . "⊑")
    ("sqsupseteq" . "⊒")
    ("inter" . "∩")
    ("Inter" . "⋂")
    ("union" . "∪")
    ("Union" . "⋃")
    ("squnion" . "⊔")
    ("Squnion" . "⨆")
    ("sqinter" . "⊓")
    ("Sqinter" . "⨅")
    ("setminus" . "∖")
    ("propto" . "∝")
    ("uplus" . "⊎")
    ("Uplus" . "⨄")
    ("noteq" . "≠")
    ("sim" . "∼")
    ("doteq" . "≐")
    ("simeq" . "≃")
    ("approx" . "≈")
    ("asymp" . "≍")
    ("cong" . "≅")
    ("smile" . "⌣")
    ("equiv" . "≡")
    ("frown" . "⌢")
    ("Join" . "⨝")
    ("bowtie" . "⋈")
    ("prec" . "≺")
    ("succ" . "≻")
    ("preceq" . "≼")
    ("succeq" . "≽")
    ("parallel" . "∥")
    ("bar" . "¦")
    ("plusminus" . "±")
    ("minusplus" . "∓")
    ("times" . "×")
    ("div" . "÷")
    ("cdot" . "⋅")
    ("star" . "⋆")
    ("bullet" . "∙")
    ("circ" . "∘")
    ("dagger" . "†")
    ("ddagger" . "‡")
    ("lhd" . "⊲")
    ("rhd" . "⊳")
    ("unlhd" . "⊴")
    ("unrhd" . "⊵")
    ("triangleleft" . "◁")
    ("triangleright" . "▷")
    ("triangle" . "▵") ; or △
    ("triangleq" . "≜")
    ("oplus" . "⊕")
    ("Oplus" . "⨁")
    ("otimes" . "⊗")
    ("Otimes" . "⨂")
    ("odot" . "⊙")
    ("Odot" . "⨀")
    ("ominus" . "⊖")
    ("oslash" . "⊘") 
    ("dots" . "…")
    ("cdots" . "⋯")
    ("Sum" . "∑")
    ("Prod" . "∏")
    ("Coprod" . "∐")
    ("infinity" . "∞")
    ("integral" . "∫")
    ("ointegral" . "∮")
    ("clubsuit" . "♣")
    ("diamondsuit" . "♢")
    ("heartsuit" . "♡")
    ("spadesuit" . "♠")
    ("aleph" . "ℵ")
    ("emptyset" . "∅")
    ("nabla" . "∇")
    ("partial" . "∂")
    ("Re" . "ℜ")
    ("Im" . "ℑ")
    ("flat" . "♭")
    ("natural" . "♮")
    ("sharp" . "♯")
    ("angle" . "∠")
    ("copyright" . "©")
    ("registered" . "®")
    ("hyphen" . "‐")
    ("inverse" . "¯¹") ; X-Symb: just "¯"
    ("onesuperior" . "¹")
    ("twosuperior" . "²")
    ("threesuperior" . "³")
    ("onequarter" . "¼")
    ("onehalf" . "½")
    ("threequarters" . "¾")
    ("ordmasculine" . "º")
    ("ordfeminine" . "ª")
    ("section" . "§")
    ("paragraph" . "¶")
    ("exclamdown" . "¡")
    ("questiondown" . "¿")
    ("euro" . "€")
    ("pounds" . "£")
    ("yen" . "¥")
    ("cent" . "¢")
    ("currency" . "¤")
    ("degree" . "°")
    ("amalg" . "⨿")
    ("mho" . "℧")
    ("lozenge" . "◊")
    ("wp" . "℘")
    ("wrong" . "≀") ;; #x002307
;;    ("struct" . "") ;; TODO
    ("acute" . "´")
    ("index" . "ı")
    ("dieresis" . "¨")
    ("cedilla" . "¸")
    ("hungarumlaut" . "ʺ")
    ("spacespace" . "⁣⁣") ;; two #x002063
;    ("module" . "") ??
    ("some" . "ϵ")
    
    ;; Not in Standard Isabelle Symbols
    ;; (some are in X-Symbols)

    ("stareq" . "≛")
    ("defeq" . "≝")
    ("questioneq" . "≟")
    ("vartheta" . "ϑ")
    ; ("o" . "ø")
    ("varpi" . "ϖ")
    ("varrho" . "ϱ")
    ("varsigma" . "ς")
    ("varphi" . "φ")
    ("hbar" . "ℏ")
    ("ell" . "ℓ")
    ("ast" . "∗")

    ("bigcirc" . "◯")
    ("bigtriangleup" . "△")
    ("bigtriangledown" . "▽")
    ("ni" . "∋")
    ("mid" . "∣")
    ("notlt" . "≮")
    ("notle" . "≰")
    ("notprec" . "⊀")
    ("notpreceq" . "⋠")
    ("notsubset" . "⊄")
    ("notsubseteq" . "⊈")
    ("notsqsubseteq" . "⋢")
    ("notgt" . "≯")
    ("notge" . "≱")
    ("notsucc" . "⊁")
    ("notsucceq" . "⋡")
    ("notsupset" . "⊅")
    ("notsupseteq" . "⊉")
    ("notsqsupseteq" . "⋣")
    ("notequiv" . "≢")
    ("notsim" . "≁")
    ("notsimeq" . "≄")
    ("notapprox" . "≉")
    ("notcong" . "≇")
    ("notasymp" . "≭")
    ("nearrow" . "↗")
    ("searrow" . "↘")
    ("swarrow" . "↙")
    ("nwarrow" . "↖")
    ("vdots" . "⋮")
    ("ddots" . "⋱")
    ("closequote" . "’")
    ("openquote" . "‘")
    ("opendblquote" . "”")
    ("closedblquote" . "“")
    ("emdash" . "—")
    ("prime" . "′")
    ("doubleprime" . "″")
    ("tripleprime" . "‴")
    ("quadrupleprime" . "⁗")
    ("nbspace" . " ")
    ("thinspace" . " ")
    ("notni" . "∌")
    ("colonequals" . "≔")

    ("foursuperior" . "⁴")
    ("fivesuperior" . "⁵")
    ("sixsuperior" . "⁶")
    ("sevensuperior" . "⁷")
    ("eightsuperior" . "⁸")
    ("ninesuperior" . "⁹")
    ;; ligatures, etc, unlikely to be useful?
    ("oe" . "œ")
    ("OE" . "Œ")
    ("ae" . "æ")
    ("AE" . "Æ")
    ("aa" . "å")
    ("AA" . "Å")
    ("o" . "ø") ;; LaTeX \o
    ("O" . "Ø") ;; LaTeX \O
    ("l" . "ł") ;; LaTeX \l
    ("L" . "Ł") ;; LaTeX \L
    ("ss" . "ß") ;; LaTeX \ss
    ("ff" . "ﬀ")
    ("fi" . "ﬁ")
    ("fl" . "ﬂ")
    ("ffi" . "ﬃ")
    ("ffl" . "ﬄ"))
  "Table mapping Isabelle ``xsymbol'' token names to Unicode strings.

You can adjust this table to add more entries, or to change entries for
glyphs that not are available in your Emacs or chosen font.

The token TNAME is made into the token \\< TNAME >.
The string mapping can be anything, but should be such that
tokens can be uniquely recovered from a decoded text; otherwise
results will be undefined when files are saved."
  :type '(repeat (cons (string :tag "Token name")
		       (string :tag "Unicode string")))
  :set 'proof-set-value
  :group 'isabelle
  :tag "Isabelle Unicode Token Mapping")


(defcustom isar-shortcut-alist
  '(; short cut, unicode string
    ("<>" . "⋄")
    ("|>" . "⊳")
    ("\\/" . "∨")
    ("/\\" . "∧")
    ("+O" . "⊕")
    ("-O" . "⊖")
    ("xO" . "⊗")
    ("/O" . "⊘")
    (".O" . "⊙")
    ("|+" . "†")
    ("|++" . "‡")
    ("<=" . "≤")
    ("|-" . "⊢")
    (">=" . "≥")
    ("-|" . "⊣")
    ("||" . "∥")
    ("==" . "≡")
    ("~=" . "≃")
    ("~~~" . "≍")
    ("~~" . "≈")
    ("~==" . "≅")
    ("|<>|" . "⋈")
    ("|=" . "⊨")
    ("=." . "≐")
    ("_|_" . "⊥")
    ("</" . "≮")
    (">=/" . "≱")
    ("=/" . "≠")
    ("==/" . "≢")
    ("~/" . "≁")
    ("~=/" . "≄")
    ("~~/" . "≉")
    ("~==/" . "≇")
    ("<-" . "←")
    ("<=" . "⇐")
    ("->" . "→")
    ("=>" . "⇒")
    ("<->" . "↔")
    ("<=>" . "⇔")
    ("|->" . "↦")
    ("<--" . "⟵")
    ("<==" . "⟸")
    ("-->" . "⟶")
    ("==>" . "⟹")
    ("<==>" . "⟷")
    ("|-->" . "⟼")
    ("<--" . "←⎯")
    ("<-->" . "⟷")
    ("<<" . "⟪")
    ("[|" . "⟦")
    (">>" . "⟫")
    ("|]" . "⟧")
    ("``" . "”")
    ("''" . "“")
    ("--" . "–")
    ("---" . "—")
    ("''" . "″")
    ("'''" . "‴")
    ("''''" . "⁗")
    (":=" . "≔")
    ;; some word shortcuts, started with backslash otherwise
    ;; too annoying.
    ("\nat" . "ℕ")
    ("\int" . "ℤ")
    ("\rat" . "ℚ")
    ("\real" . "ℝ")
    ("\complex" . "ℂ")
    ("\euro" . "€")
    ("\yen" . "¥")
    ("\cent" . "¢"))
  "Shortcut key sequence table for Unicode strings.

You can adjust this table to add more entries, or to change entries for
glyphs that not are available in your Emacs or chosen font.

These shortcuts are only used for input; no reverse conversion is
performed.  But if tokens exist for the target of shortcuts, they
will be used on saving the buffer."
  :type '(repeat (cons (string :tag "Shortcut sequence")
		       (string :tag "Unicode string")))
  :set 'proof-set-value
  :group 'isabelle
  :tag "Isabelle Unicode Token Mapping")

  


;;
;; prover symbol support 
;;

(eval-after-load "isar" 
  '(setq 
    proof-xsym-activate-command
    (isar-markup-ml "change print_mode (insert (op =) \"xsymbols\")")
    proof-xsym-deactivate-command
    (isar-markup-ml "change print_mode (remove (op =) \"xsymbols\")")))



(provide 'isar-unicode-tokens)

;;; isar-unicode-tokens.el ends here
