;;; company-cabal-fields.el -- cabal field definitions.
;;
;;; Commentary:
;;
;; Automatically generated by tools/cabal-fields.hs with Cabal-2.0.0.2.
;;
;;; Code:

(defconst company-cabal--benchmark-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("autogen-modules"
     "build-depends"
     "build-tool-depends"
     "build-tools"
     "buildable"
     "c-sources"
     "cc-options"
     "cpp-options"
     "default-extensions"
     "default-language"
     "extensions"
     "extra-framework-dirs"
     "extra-ghci-libraries"
     "extra-lib-dirs"
     "extra-libraries"
     "frameworks"
     "ghc-options"
     "ghc-prof-options"
     "ghc-shared-options"
     "ghcjs-options"
     "ghcjs-prof-options"
     "ghcjs-shared-options"
     "hs-source-dirs"
     "hugs-options"
     "include-dirs"
     "includes"
     "install-includes"
     "jhc-options"
     "js-sources"
     "ld-options"
     "main-is"
     "mixins"
     "nhc98-options"
     "other-extensions"
     "other-languages"
     "other-modules"
     "pkgconfig-depends"
     "type")))

(defconst company-cabal--executable-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("autogen-modules"
     "build-depends"
     "build-tool-depends"
     "build-tools"
     "buildable"
     "c-sources"
     "cc-options"
     "cpp-options"
     "default-extensions"
     "default-language"
     "extensions"
     "extra-framework-dirs"
     "extra-ghci-libraries"
     "extra-lib-dirs"
     "extra-libraries"
     "frameworks"
     "ghc-options"
     "ghc-prof-options"
     "ghc-shared-options"
     "ghcjs-options"
     "ghcjs-prof-options"
     "ghcjs-shared-options"
     "hs-source-dirs"
     "hugs-options"
     "include-dirs"
     "includes"
     "install-includes"
     "jhc-options"
     "js-sources"
     "ld-options"
     "main-is"
     "mixins"
     "nhc98-options"
     "other-extensions"
     "other-languages"
     "other-modules"
     "pkgconfig-depends"
     "scope")))

(defconst company-cabal--flag-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("default"
     "description"
     "manual")))

(defconst company-cabal--library-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("autogen-modules"
     "build-depends"
     "build-tool-depends"
     "build-tools"
     "buildable"
     "c-sources"
     "cc-options"
     "cpp-options"
     "default-extensions"
     "default-language"
     "exposed"
     "exposed-modules"
     "extensions"
     "extra-framework-dirs"
     "extra-ghci-libraries"
     "extra-lib-dirs"
     "extra-libraries"
     "frameworks"
     "ghc-options"
     "ghc-prof-options"
     "ghc-shared-options"
     "ghcjs-options"
     "ghcjs-prof-options"
     "ghcjs-shared-options"
     "hs-source-dirs"
     "hugs-options"
     "include-dirs"
     "includes"
     "install-includes"
     "jhc-options"
     "js-sources"
     "ld-options"
     "mixins"
     "nhc98-options"
     "other-extensions"
     "other-languages"
     "other-modules"
     "pkgconfig-depends"
     "reexported-modules"
     "signatures")))

(defconst company-cabal--pkgdescr-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("author"
     "bug-reports"
     "build-type"
     "cabal-version"
     "category"
     "copyright"
     "data-dir"
     "data-files"
     "description"
     "extra-doc-files"
     "extra-source-files"
     "extra-tmp-files"
     "homepage"
     "license"
     "license-file"
     "license-files"
     "maintainer"
     "name"
     "package-url"
     "stability"
     "synopsis"
     "tested-with"
     "version")))

(defconst company-cabal--sourcerepo-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("branch"
     "location"
     "module"
     "subdir"
     "tag"
     "type")))

(defconst company-cabal--testsuite-fields
  (mapcar
   (lambda (x) (propertize x :type 'field))
   '("autogen-modules"
     "build-depends"
     "build-tool-depends"
     "build-tools"
     "buildable"
     "c-sources"
     "cc-options"
     "cpp-options"
     "default-extensions"
     "default-language"
     "extensions"
     "extra-framework-dirs"
     "extra-ghci-libraries"
     "extra-lib-dirs"
     "extra-libraries"
     "frameworks"
     "ghc-options"
     "ghc-prof-options"
     "ghc-shared-options"
     "ghcjs-options"
     "ghcjs-prof-options"
     "ghcjs-shared-options"
     "hs-source-dirs"
     "hugs-options"
     "include-dirs"
     "includes"
     "install-includes"
     "jhc-options"
     "js-sources"
     "ld-options"
     "main-is"
     "mixins"
     "nhc98-options"
     "other-extensions"
     "other-languages"
     "other-modules"
     "pkgconfig-depends"
     "test-module"
     "type")))

(defconst company-cabal--section-field-alist
  (list (cons "benchmark" company-cabal--benchmark-fields)
        (cons "executable" company-cabal--executable-fields)
        (cons "flag" company-cabal--flag-fields)
        (cons "library" company-cabal--library-fields)
        (cons "source-repository" company-cabal--sourcerepo-fields)
        (cons "test-suite" company-cabal--testsuite-fields)))

(defconst company-cabal--sections
  (mapcar (lambda (cs) (propertize  (car cs) :type 'section))
          company-cabal--section-field-alist))

(defconst company-cabal--build-type-values
  (mapcar (lambda (x) (propertize x :type 'value))
          '("Simple" "Configure" "Make" "Custom")))

(defconst company-cabal--benchmark-type-values
  (mapcar (lambda (x) (propertize x :type 'value))
          '("exitcode-stdio-1.0")))

(defconst company-cabal--testsuite-type-values
  (mapcar (lambda (x) (propertize x :type 'value))
          '("exitcode-stdio-1.0" "detailed-1.0")))

(defconst company-cabal--sourcerepo-type-values
  (mapcar (lambda (x) (propertize x :type 'value))
          '("darcs" "git" "svn" "cvs" "mercurial" "hg" "bazaar" "bzr"
            "arch" "monotone")))

(provide 'company-cabal-fields)
;;; company-cabal-fields.el ends here
