share_root: [
  "tuareg.el" {"emacs/site-lisp/tuareg.el"}
  "tuareg_indent.el" {"emacs/site-lisp/tuareg_indent.el"}
  "ocamldebug.el" {"emacs/site-lisp/ocamldebug.el"}
  "tuareg-site-file.el" {"emacs/site-lisp/tuareg-site-file.el"}
  "?tuareg.elc" {"emacs/site-lisp/tuareg.elc"}
  "?tuareg_indent.elc" {"emacs/site-lisp/tuareg_indent.elc"}
  "?ocamldebug.elc" {"emacs/site-lisp/ocamldebug.elc"}
  "?tuareg-site-file.elc" {"emacs/site-lisp/tuareg-site-file.elc"}
]
