* Change Log
  All notable changes to this project will be documented in this file.
  The format is based on [[http://keepachangelog.com/][Keep a Changelog]].

** Unreleased
   See [[https://github.com/iqbalansari/emacs-emojify/compare/v0.4...HEAD][Changes]]

*** Fixed
    - Do not try emojifying areas larger than 5000 points
    - Fix display of emojis containing the plus sign (eg. ~:+1:~)
    - Fix backspace to delete complete emojis in ~org-mode~
*** Added
    - New command ~emojify-describe-emoji-at-point~ can be used to view help about emoji displayed at point.
    - New command ~emojify-describe-emoji~ can be used to view help about a emoji.
    - New command ~emojify-list-emojis~ for listing all the emojis
    - Support for displaying emojis in ~company-mode~ buffers
    - New function ~emojify-completing-read~ to read an emoji from the user
    - New function ~emojify-string~ can be used to add relevant text-properties to strings so that emojis in them are displayed
    - Support for new text property ~emojify-inhibit~ it can be set by third party packages to inhibit the display of certain parts of buffer as emoji
    - Support for new text property ~emojify-force-display~ it can be set by third party packages to force the display of certain parts of buffer as emoji

** v0.4 - 2016-09-28
   See [[https://github.com/iqbalansari/emacs-emojify/compare/v0.3...v0.4][Changes]]

*** Removed
    - The customizable variable ~emojify-image-dir~ has been removed since it did not interact well with emojify-emojis-dir.
*** Fixed
    - Emojify mode is disabled in ~magit-diff-mode~, ~ibuffer-mode~ and ~debugger-mode~.
    - Emojify now does not rely on deprecated ~point-entered~ and ~point-left~ text properties for implementing uncovering logic, this makes emojify compatible with Emacs 25.1
    - Emojify mode is disabled when buffer switches to unibyte encoding
*** Changed
    - Emoji images are now downloaded lazily instead of being packaged with code, this also makes it possible to use emoji sets other than EmojiOne.
    - The behaviour when point enters an emoji in ~isearch-mode~ is now customizable, earlier the emoji was revealed by default. See ~emojify-reveal-on-isearch~.
    - Images from EmojiOne v2.2.6 are used by default
*** Added
    - ~unicode~ emojis appearing in source code are rendered by default.
    - New command ~emojify-apropos-emoji~ can be used to search emojis matching given regex.
    - New command ~emojify-insert-emoji~ can be used to insert emojis with completion.
    - Users can now define custom emojis using ~emojify-user-emojis~
    - Emojify can now display composed text as emojis, this enables rendering of symbols used by ~prettify-symbols-mode~ or ~org-bullets-mode~ as emojis. See ~emojify-composed-text-p~

** v0.3 - 2015-12-21
   See [[https://github.com/iqbalansari/emacs-emojify/compare/v0.2...v0.3][Changes]]

*** Fixed
    - Multiple non-ascii emojis in sequence are displayed properly.
    - Treat tuareg-mode as programming mode.
*** Added
    - Deletion commands remove complete emoji instead of removing a single character.
    - Emoji backgrounds are calculated based on the face at point.

** v0.2 - 2015-09-15
   See [[https://github.com/iqbalansari/emacs-emojify/compare/v0.1...v0.2][Changes]]

*** Removed
    - The variable ~emojify-emoji-style~ has been replaced with ~emojify-emoji-styles~

*** Added
    - The package can now display unicode emojis as well

** v0.1 - 2015-09-14
   Initial public release
